Repository Consensys/teku, pull requests merged in 2018-12, with the labels that each got.

#118 Removing old references to BeaconChain
  beaconchain/build.gradle
  beaconchain/src/main/java/net/consensys/beaconchain/App.java
  beaconchain/src/main/java/net/consensys/beaconchain/Constants.java
  beaconchain/src/main/java/net/consensys/beaconchain/controllers/ServiceController.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainBlocks/BeaconBlock.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainBlocks/BeaconBlockBody.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainBlocks/ProposalSignedData.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainOperations/Attestation.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainOperations/AttestationData.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainOperations/CasperSlashing.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainOperations/Deposit.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainOperations/DepositData.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainOperations/DepositParameters.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainOperations/Exit.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainOperations/ProposerSlashing.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainOperations/SlashableVoteData.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainState/CandidatePoWReceiptRootRecord.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainState/CrosslinkRecord.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainState/ForkData.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainState/PendingAttestationRecord.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainState/ShardCommittee.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainState/ShardReassignmentRecord.java
  beaconchain/src/main/java/net/consensys/beaconchain/datastructures/BeaconChainState/ValidatorRecord.java
  beaconchain/src/main/java/net/consensys/beaconchain/factories/EventBusFactory.java
  beaconchain/src/main/java/net/consensys/beaconchain/factories/ServiceFactory.java
  beaconchain/src/main/java/net/consensys/beaconchain/services/BeaconChainService.java
  beaconchain/src/main/java/net/consensys/beaconchain/services/PowchainService.java
  beaconchain/src/main/java/net/consensys/beaconchain/services/ServiceInterface.java
  beaconchain/src/main/java/net/consensys/beaconchain/state/BeaconState.java
  beaconchain/src/test/java/net/consensys/beaconchain/state/BeaconStateTest.java
  ethereum/core/src/main/java/net/consensys/beaconchain/ethereum/mainnet/EthHash.java
  ethereum/core/src/test/java/net/consensys/beaconchain/ethereum/core/EthHashTest.java
Labels: bug 🐞

#125 Changes class fields to private and adds getter and setter methods
  artemis/src/main/java/tech/pegasys/artemis/Artemis.java
  artemis/src/main/java/tech/pegasys/artemis/controllers/ServiceController.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainBlocks/BeaconBlockBody.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainBlocks/ProposalSignedData.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainOperations/Attestation.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainOperations/AttestationData.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainOperations/CasperSlashing.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainOperations/Deposit.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainOperations/DepositData.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainOperations/DepositInput.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainOperations/Exit.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainOperations/ProposerSlashing.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainOperations/SlashableVoteData.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainState/CandidatePoWReceiptRootRecord.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainState/CrosslinkRecord.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainState/ForkData.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainState/PendingAttestationRecord.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainState/ShardCommittee.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainState/ShardReassignmentRecord.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainState/ValidatorRecord.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/BeaconChainState/ValidatorRegistryDeltaBlock.java
  artemis/src/main/java/tech/pegasys/artemis/state/BeaconState.java
  artemis/src/test/java/tech/pegasys/artemis/state/BeaconStateTest.java
  pow/src/main/resources/README.md
Labels: code style 💅

#129 Service Threading, Cleanup, and SIGTERM
  .gitignore
  artemis/src/main/java/tech/pegasys/artemis/Artemis.java
  artemis/src/main/java/tech/pegasys/artemis/services/ServiceController.java
  artemis/src/main/java/tech/pegasys/artemis/services/ServiceFactory.java
  artemis/src/main/java/tech/pegasys/artemis/services/ServiceInterface.java
  artemis/src/main/java/tech/pegasys/artemis/services/beaconchain/BeaconChainService.java
  artemis/src/main/java/tech/pegasys/artemis/services/beaconchain/SlotScheduler.java
  artemis/src/main/java/tech/pegasys/artemis/services/powchain/PowchainService.java
Labels: bug 🐞, enhancement 🕵️‍♀️

#135 Update README.md
  README.md
Labels: documentation :memo:

#139 Updated readme for pow package
  pow/src/main/resources/README.md
Labels: documentation :memo:

#140 Update VRC contract to reflect Eth2 spec
  pow/src/main/java/tech/pegasys/artemis/pow/contract/ValidatorRegistrationContract.java
  pow/src/main/resources/truffle/contracts/vrc.v.py
Labels: enhancement 🕵️‍♀️

#141 Deep copy for BeaconState
  artemis/build.gradle
  artemis/src/main/java/tech/pegasys/artemis/services/beaconchain/StateTransition.java
  artemis/src/main/java/tech/pegasys/artemis/state/BeaconState.java
  artemis/src/main/java/tech/pegasys/artemis/state/InterfaceAdapter.java
  artemis/src/test/java/tech/pegasys/artemis/state/BeaconStateTest.java
Labels: enhancement 🕵️‍♀️
