Repository Consensys/teku, pull requests merged in 2019-01, with the labels that each got.

#120 Process deposits
  artemis/src/main/java/tech/pegasys/artemis/state/BeaconState.java
  artemis/src/test/java/tech/pegasys/artemis/state/BeaconStateTest.java
Labels: blocked by another PR/issue 💔, enhancement 🕵️‍♀️

#152 UInt64 to long
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainblocks/BeaconBlock.java
  artemis/src/main/java/tech/pegasys/artemis/services/beaconchain/StateTransition.java
  artemis/src/main/java/tech/pegasys/artemis/state/BeaconState.java
  artemis/src/test/java/tech/pegasys/artemis/state/BeaconStateTest.java
Labels: enhancement 🕵️‍♀️

#144 Initial Epoch Processing Logic Implementation
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/AttestationData.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/ValidatorRecord.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/Validators.java
  artemis/src/main/java/tech/pegasys/artemis/services/beaconchain/StateTransition.java
  artemis/src/main/java/tech/pegasys/artemis/state/BeaconState.java
  artemis/src/main/java/tech/pegasys/artemis/state/util/AttestationUtil.java
  artemis/src/main/java/tech/pegasys/artemis/state/util/BlockValidationException.java
  artemis/src/main/java/tech/pegasys/artemis/state/util/EpochProcessorUtil.java
  artemis/src/main/java/tech/pegasys/artemis/state/util/ValidatorsUtil.java
  artemis/src/test/java/tech/pegasys/artemis/state/BeaconStateTest.java
Labels: enhancement 🕵️‍♀️, in progress 👩‍💻

#153 Shuffle and split accept ArrayList of generic type objects
  artemis/src/main/java/tech/pegasys/artemis/state/BeaconState.java
  artemis/src/test/java/tech/pegasys/artemis/state/BeaconStateTest.java
Labels: enhancement 🕵️‍♀️

#159 Gradle 5.1 Upgrade
  artemis/build.gradle
  build.gradle
  gradle/check-licenses.gradle
  gradle/versions.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  pow/build.gradle
  settings.gradle
Labels: enhancement 🕵️‍♀️

#164 Cleanup Gradle Setup
  artemis/build.gradle
  build.gradle
  crypto/build.gradle
  crypto/src/main/java/tech/pegasys/artemis/crypto/Hash.java
  errorprone-checks/build.gradle
  ethereum/core/build.gradle
  ethereum/core/src/test/java/tech/pegasys/artemis/ethereum/core/AddressTest.java
  ethereum/rlp/build.gradle
  ethereum/rlp/src/jmh/java/tech/pegasys/artemis/ethereum/rlp/RLPBench.java
  gradle/check-licenses.gradle
  gradle/versions.gradle
  pow/build.gradle
  util/build.gradle
  util/src/main/java/tech/pegasys/artemis/util/message/BouncyCastleMessageDigestFactory.java
  util/src/test/java/tech/pegasys/artemis/util/bytes/BytesValueTest.java
Labels: code style 💅

#162 Remove unnecessary Pantheon implementation primitives
  util/src/main/java/tech/pegasys/artemis/util/bytes/ArrayWrappingBytes1.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/ArrayWrappingBytes3.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/ArrayWrappingBytes48.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/Bytes1.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/Bytes1s.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/Bytes3.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/Bytes3s.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/Bytes48.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/Bytes48s.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/MutableArrayWrappingBytes1.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/MutableArrayWrappingBytes3.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/MutableArrayWrappingBytes48.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/MutableBytes1.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/MutableBytes3.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/MutableBytes48.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/WrappingBytes3.java
  util/src/main/java/tech/pegasys/artemis/util/bytes/WrappingBytes48.java
  util/src/main/java/tech/pegasys/artemis/util/uint/UInt256Bytes.java
  util/src/test/java/tech/pegasys/artemis/util/bytes/Bytes1Test.java
  util/src/test/java/tech/pegasys/artemis/util/bytes/Bytes3Test.java
  util/src/test/java/tech/pegasys/artemis/util/bytes/Bytes48Test.java
Labels: code style 💅

#168 Adds remaining helper functions from new spec update
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/SlashableVoteData.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/ShardCommittee.java
  artemis/src/main/java/tech/pegasys/artemis/state/BeaconState.java
  artemis/src/main/java/tech/pegasys/artemis/state/util/EpochProcessorUtil.java
  artemis/src/main/java/tech/pegasys/artemis/state/util/ValidatorsUtil.java
  artemis/src/test/java/tech/pegasys/artemis/state/BeaconStateTest.java
  artemis/src/test/java/tech/pegasys/artemis/state/util/ValidatorsUtilTest.java
Labels: enhancement 🕵️‍♀️

#177 Uncomments test cases.
  artemis/src/test/java/tech/pegasys/artemis/state/BeaconStateTest.java
Labels: code style 💅, enhancement 🕵️‍♀️

#179 Some code cleanup.
  artemis/src/main/java/tech/pegasys/artemis/Artemis.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainblocks/BeaconBlock.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainblocks/BeaconBlockBody.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainblocks/ProposalSignedData.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/Attestation.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/AttestationData.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/AttestationDataAndCustodyBit.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/CasperSlashing.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/Deposit.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/DepositData.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/DepositInput.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/Exit.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/ProposerSlashing.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/SlashableVoteData.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/CandidatePoWReceiptRootRecord.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/CrosslinkRecord.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/ForkData.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/PendingAttestationRecord.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/ShardCommittee.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/ShardReassignmentRecord.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/ValidatorRecord.java
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/ValidatorRegistryDeltaBlock.java
  artemis/src/main/java/tech/pegasys/artemis/state/BeaconState.java
  artemis/src/main/java/tech/pegasys/artemis/state/util/AttestationUtil.java
  artemis/src/main/java/tech/pegasys/artemis/state/util/EpochProcessorUtil.java
  artemis/src/main/java/tech/pegasys/artemis/state/util/SlotProcessorUtil.java
  artemis/src/main/java/tech/pegasys/artemis/state/util/ValidatorsUtil.java
  artemis/src/test/java/tech/pegasys/artemis/state/BeaconStateTest.java
Labels: code style 💅

#121 Initial beacon state transition function
  artemis/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/ValidatorRecord.java
  artemis/src/main/java/tech/pegasys/artemis/state/BeaconState.java
Labels: enhancement 🕵️‍♀️

#191 Add Unicode Support in Jenkins Build
  Dockerfile
  Jenkinsfile
Labels: bug 🐞, in progress 🚧

#188 Replaced UInt64 with UnsignedLong
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainblocks/ProposalSignedData.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/AttestationData.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/Deposit.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/DepositData.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/Exit.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/LatestBlockRoots.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/CandidatePoWReceiptRootRecord.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/CrosslinkRecord.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/ForkData.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/PendingAttestationRecord.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/ShardCommittee.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/ShardReassignmentRecord.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/ValidatorRecord.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainstate/ValidatorRegistryDeltaBlock.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/BeaconState.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/util/AttestationUtil.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/util/EpochProcessorUtil.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/util/SlotProcessorUtil.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/util/ValidatorsUtil.java
  ethereum/beaconchain/src/test/java/tech/pegasys/artemis/state/BeaconStateTest.java
  ethereum/beaconchain/src/test/java/tech/pegasys/artemis/state/StateTransitionTest.java
  ethereum/beaconchain/src/test/java/tech/pegasys/artemis/state/util/ValidatorsUtilTest.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSVerify.java
  util/src/main/java/tech/pegasys/artemis/util/uint/UInt64.java
  util/src/test/java/tech/pegasys/artemis/util/uint/UInt64Test.java
Labels: code style 💅, enhancement 🕵️‍♀️

#195 Set up scaffolding for ChainStorageService
  artemis/build.gradle
  artemis/src/main/java/tech/pegasys/artemis/Artemis.java
  gradle.properties
  services/chainstorage/build.gradle
  services/chainstorage/src/main/java/tech/pegasys/artemis/services/chainstorage/ChainStorageService.java
  services/src/main/java/tech/pegasys/artemis/services/ServiceController.java
  settings.gradle
Labels: enhancement 🕵️‍♀️

#198 Fix bug in BeaconState:bytes3ToInt, add more unit test coverage.
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/BeaconState.java
  ethereum/beaconchain/src/test/java/tech/pegasys/artemis/state/BeaconStateTest.java
Labels: bug 🐞

#199 Created StateTreeManager scaffolding
  ethereum/beaconchain/build.gradle
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/StateTreeManager.java
  networking/p2p/build.gradle
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
  services/beaconchain/src/main/java/tech/pegasys/artemis/services/beaconchain/BeaconChainService.java
Labels: enhancement 🕵️‍♀️

#209 Move slot scheduler under state package
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/SlotScheduler.java
  services/beaconchain/src/main/java/tech/pegasys/artemis/services/beaconchain/BeaconChainService.java
Labels: code style 💅

#210 renamed P2PService to BeaconNodeService
  artemis/build.gradle
  artemis/src/main/java/tech/pegasys/artemis/Artemis.java
  services/beaconchain/build.gradle
  services/beaconnode/build.gradle
  services/beaconnode/src/main/java/tech/pegasys/artemis/services/beaconnode/BeaconNodeService.java
  services/src/main/java/tech/pegasys/artemis/services/ServiceController.java
  settings.gradle
Labels: enhancement 🕵️‍♀️

#167 updateJustification: Validators justifying the epoch boundary block at the start of the current epoch
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/StateTransition.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/util/AttestationUtil.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/util/BeaconStateUtil.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/util/EpochProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#216 slot processer is now calling the correct methods
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/StateTransition.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/StateTreeManager.java
Labels: enhancement 🕵️‍♀️

#217 implemented hash_tree_root
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/Constants.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainblocks/BeaconBlock.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainblocks/BeaconBlockBody.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainblocks/ProposalSignedData.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/Attestation.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/AttestationData.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/CasperSlashing.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/Deposit.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/DepositData.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/Exit.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/ProofOfCustodyChallenge.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/ProofOfCustodyResponse.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/ProofOfCustodySeedChange.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/ProposerSlashing.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/datastructures/beaconchainoperations/SlashableVoteData.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/BeaconState.java
Labels: enhancement 🕵️‍♀️

#220 Merkle_Root and Block Processing Part 1
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/BeaconState.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/StateTransition.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/StateTreeManager.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/util/AttestationUtil.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/util/BeaconStateUtil.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/util/BlockProcessorUtil.java
  ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/util/SlotProcessorUtil.java
  ethereum/beaconchain/src/test/java/tech/pegasys/artemis/state/BeaconStateTest.java
  ethereum/beaconchain/src/test/java/tech/pegasys/artemis/state/StateTransitionTest.java
Labels: enhancement 🕵️‍♀️
