Repository Consensys/teku, pull requests merged in 2019-05, with the labels that each got.

#616 Rando Fixes
  README.md
  artemis.env
  artemis/src/main/java/tech/pegasys/artemis/Artemis.java
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  config/rlpxConfig.0.toml
  config/rlpxConfig.1.toml
  config/rlpxConfig.2.toml
  scripts/dockerBuild.sh
Labels: enhancement 🕵️‍♀️

#617 Fixes breaking BeaconStateUtil test
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtilTest.java
Labels: testing 💯🖍

#619 Fixes bug in get_randao_mix that breaks tests
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateWithCacheTest.java
Labels: testing 💯🖍

#620 Genesis slot and genesis epoch = 0 in config files
  config/config.toml
  config/demoConfig.0.toml
  config/demoConfig.1.toml
  config/demoConfig.2.toml
  config/demoConfig.3.toml
  config/testConfig.0.toml
  config/testConfig.1.toml
  config/testConfig.2.toml
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#618 Update the `run` script to be more general
  .gitignore
  scripts/demo.sh
  scripts/run.sh
  scripts/utils.sh
Labels: enhancement 🕵️‍♀️

#624 run script and configs
  README.md
  artemis/src/test/java/tech/pegasys/artemis/BeaconNodeIntegrationTest.java
  config/config.toml
  config/demoConfig.0.toml
  config/demoConfig.1.toml
  config/demoConfig.2.toml
  config/demoConfig.3.toml
  config/testConfig.0.toml
  config/testConfig.1.toml
  config/testConfig.2.toml
  scripts/demo_3.sh
  scripts/run.sh
  scripts/utils.sh
  util/src/main/java/tech/pegasys/artemis/util/cli/CommandLineArguments.java
  util/src/main/java/tech/pegasys/artemis/util/config/ArtemisConfiguration.java
  util/src/test/java/tech/pegasys/artemis/util/config/ArtemisConfigurationTest.java
Labels: enhancement 🕵️‍♀️

#611 Upgrade SSZ to v0.5.1
  data/adapter/src/main/java/tech/pegasys/artemis/data/adapter/TimeSeriesAdapter.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBody.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockHeader.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1Data.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1DataVote.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Attestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationDataAndCustodyBit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttesterSlashing.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Deposit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositInput.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/ProposerSlashing.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/SlashableAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Transfer.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/VoluntaryExit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/BeaconState.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Crosslink.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Fork.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/PendingAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Validator.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/AttestationUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconBlockUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/ForkTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/LmdGhost.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  lib/cava-ssz-1.0.0-dev.jar
  util/src/main/java/tech/pegasys/artemis/util/hashtree/HashTreeUtil.java
  util/src/main/java/tech/pegasys/artemis/util/hashtree/Merkleizable.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: enhancement 🕵️‍♀️

#626 BeaconState SSZ fixes, and run spotless.
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Attestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Deposit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/ProposerSlashing.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/SlashableAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Transfer.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/VoluntaryExit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/BeaconState.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/PendingAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Validator.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  util/src/main/java/tech/pegasys/artemis/util/hashtree/HashTreeUtil.java
  util/src/main/java/tech/pegasys/artemis/util/hashtree/Merkleizable.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: enhancement 🕵️‍♀️

#627 SSZ Debugging
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositInput.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSPublicKey.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSSignature.java
  util/src/main/java/tech/pegasys/artemis/util/hashtree/HashTreeUtil.java
Labels: bug 🐞

#628 Fixes processPenaltiesAndExitsTest
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
Labels: testing 💯🖍

#630 Revert get_domain calculation order change after clarification.
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
Labels: bug 🐞

#631 Revert "Revert get_domain calculation order change after clarification."
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
Labels: bug 🐞

#632 Swappable Timers
  artemis/src/test/java/tech/pegasys/artemis/BeaconNodeIntegrationTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/SlotScheduler.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  gradle/versions.gradle
  services/beaconchain/src/main/java/tech/pegasys/artemis/services/beaconchain/BeaconChainService.java
  util/build.gradle
  util/src/main/java/tech/pegasys/artemis/util/time/JavaTimer.java
  util/src/main/java/tech/pegasys/artemis/util/time/QuartzTimer.java
  util/src/main/java/tech/pegasys/artemis/util/time/Timer.java
Labels: enhancement 🕵️‍♀️

#639 Resolve genesis state transition bug. Got to set the state root...
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: bug 🐞

#641 Remove expectation to pass length mixin when reading BLS primitives.
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSPublicKey.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSSignature.java
Labels: bug 🐞

#653 Fixed index out of bounds issue in TimerSeriesAdapter
  data/adapter/src/main/java/tech/pegasys/artemis/data/adapter/TimeSeriesAdapter.java
  data/src/main/java/tech/pegasys/artemis/data/RawRecord.java
Labels: bug 🐞

#654 Fixes null pointer exception
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#657 ChainStorage NullPointer Fix
  artemis.env
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorage.java
Labels: bug 🐞

#658 Add hash_tree_root support to HistoricalBatch.
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/HistoricalBatch.java
  util/src/main/java/tech/pegasys/artemis/util/hashtree/HashTreeUtil.java
Labels: enhancement 🕵️‍♀️

#660 Fixes #636 - Move commandline arguments to toml config file
  README.md
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  artemis/src/test/java/tech/pegasys/artemis/BeaconNodeIntegrationTest.java
  config/config.toml
  data/provider/src/main/java/tech/pegasys/artemis/data/provider/EventHandler.java
  services/powchain/src/main/java/tech/pegasys/artemis/services/powchain/PowchainService.java
  util/src/main/java/tech/pegasys/artemis/util/cli/CommandLineArguments.java
  util/src/main/java/tech/pegasys/artemis/util/config/ArtemisConfiguration.java
Labels: enhancement 🕵️‍♀️

#665 Minor fixes to script and logging
  README.md
  build.gradle
  data/adapter/src/main/java/tech/pegasys/artemis/data/adapter/TimeSeriesAdapter.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  scripts/utils.sh
Labels: enhancement 🕵️‍♀️

#666 Added a script that updates configuration variables
  scripts/configurator.sh
Labels: enhancement 🕵️‍♀️

#645 Remove merkle_root in favor of hash_tree_root functions
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#647 Refactor process slashings
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#675 Add Missing Merkleizable Flag to Select Composite Types
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1DataVote.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/PendingAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Validator.java
Labels: bug 🐞

#679 Fix equals error
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: bug 🐞

#680 Remove internal event bus from new event and use external bus
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/GenesisHeadStateEvent.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: bug 🐞

#682 Break inheritance connection between events to fix duplicate event bug.
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/GenesisHeadStateEvent.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: bug 🐞

#683 Implements validator changes from spec version 0.6.1
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: bug 🐞

#685 Fix justified epoch error
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: bug 🐞
