Repository Consensys/teku, pull requests merged in 2019-04, with the labels that each got.

#542 initial implementation of Gossip specification
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipCodec.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipMessage.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipMethod.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/SSZBlock.java
  networking/p2p/src/test/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipCodecTest.java
  networking/p2p/src/test/java/tech/pegasys/artemis/networking/p2p/hobbits/JsonRoundtripTest.java
  networking/p2p/src/test/resources/log4j2.xml
Labels: enhancement 🕵️‍♀️

#546 Implement HistoricalBatch Datastructure
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/HistoricalBatch.java
Labels: enhancement 🕵️‍♀️

#548 networked nodes
  artemis/src/test/java/tech/pegasys/artemis/BeaconNodeIntegrationTest.java
  config/testConfig.0.toml
  config/testConfig.1.toml
  config/testConfig.2.toml
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/RLPxP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/api/P2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/Codec.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipCodec.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/HobbitsSocketHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/Peer.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/RPCCodec.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/SSZBlock.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: enhancement 🕵️‍♀️

#551 multiNodeFix
  config/config.toml
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/AttestationUtil.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: enhancement 🕵️‍♀️

#557 Update helper functions documentation
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Constants.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBody.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockHeader.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositInput.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/PendingAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/AttestationUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/ValidatorsUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtilTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/LmdGhost.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/SlotProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
  util/src/main/java/tech/pegasys/artemis/util/hashtree/HashTreeUtil.java
Labels: documentation :memo:

#558 Demo Script
  .gitignore
  README.md
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  config/demoConfig.0.toml
  config/demoConfig.1.toml
  config/demoConfig.2.toml
  config/demoConfig.3.toml
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/HobbitsSocketHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/Peer.java
  scripts/demo.sh
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageServer.java
Labels: enhancement 🕵️‍♀️

#555 Updates function signatures, adds and updates docstrings, removes duplicate functions
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Constants.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBody.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositInput.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/AttestationUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/ValidatorsUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtilTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/LmdGhost.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/SlotProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
  util/src/main/java/tech/pegasys/artemis/util/hashtree/HashTreeUtil.java
Labels: documentation :memo:, enhancement 🕵️‍♀️

#562 Integrate plumtree library into gossip
  artemis/build.gradle
  gradle/versions.gradle
  networking/p2p/build.gradle
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsSubProtocolHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/Codec.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipCodec.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipMessage.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/HobbitsSocketHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/Peer.java
  networking/p2p/src/test/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipCodecTest.java
Labels: enhancement 🕵️‍♀️

#564 Minor Fixes to Logging
  README.md
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsSubProtocolHandler.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: enhancement 🕵️‍♀️

#567 Ignore Dup messages
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsSubProtocol.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsSubProtocolHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/RLPxP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/HobbitsSocketHandler.java
  networking/p2p/src/test/java/tech/pegasys/artemis/networking/p2p/HobbitsSubProtocolTest.java
Labels: enhancement 🕵️‍♀️

#570 Blocks now finalizing in networked mode Part 1
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/AttestationUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  scripts/demo.sh
  scripts/demo_3.sh
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorage.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: enhancement 🕵️‍♀️

#561 Cleans up comments, consistent styling for function and param names
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockHeader.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositInput.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Transfer.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/VoluntaryExit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/PendingAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/ValidatorsUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtilTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/LmdGhost.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: code style 💅, documentation :memo:

#574 Minor fixes
  README.md
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSAggregate.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSVerify.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: bug 🐞

#580 Make get_beacon_proposer_index safe for next epoch
  validator/client/src/main/java/tech/pegasys/artemis/validator/client/ValidatorClient.java
Labels: enhancement 🕵️‍♀️

#577 Minor fixes to build errors in codebase
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Fork.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateWithCacheTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtilTest.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/StateTransitionTest.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
Labels: enhancement 🕵️‍♀️

#579 Slash proposers based on epoch instead of slot
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#582 Send attestations
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  scripts/demo.sh
  scripts/demo_3.sh
  storage/build.gradle
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorage.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: enhancement 🕵️‍♀️

#554 Align Datastructures to Spec and Add Fixed-Length Tuple Support
  README.md
  artemis/build.gradle
  data/adapter/build.gradle
  data/build.gradle
  data/provider/build.gradle
  ethereum/datastructures/build.gradle
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockHeader.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1Data.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Deposit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositInput.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/BeaconState.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Crosslink.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Fork.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/HistoricalBatch.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Validator.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/statetransition/build.gradle
  gradle/versions.gradle
  lib/cava-ssz-1.0.0-dev.jar
  util/build.gradle
Labels: enhancement 🕵️‍♀️

#585 Change lmdGhost & run spotlessApply
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1Data.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Deposit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/BeaconState.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Crosslink.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Fork.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/HistoricalBatch.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/LmdGhost.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  validator/client/src/main/java/tech/pegasys/artemis/validator/client/ValidatorClient.java
Labels: enhancement 🕵️‍♀️

#586 Sleep Interrupt
  artemis/src/main/resources/log4j2.xml
  artemis/src/test/java/tech/pegasys/artemis/BeaconNodeIntegrationTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/HobbitsSocketHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/Peer.java
  services/beaconchain/src/main/java/tech/pegasys/artemis/services/beaconchain/BeaconChainService.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
Labels: enhancement 🕵️‍♀️

#587 Fix build errors
  artemis/build.gradle
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/BeaconState.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/LmdGhost.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: bug 🐞

#588 Fixes indexing error from spec in verify_merkle_branch
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/LmdGhost.java
Labels: enhancement 🕵️‍♀️

#590 Initializes deposit proof at correct array size
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/LmdGhost.java
Labels: enhancement 🕵️‍♀️

#591 Fixes build errors from tests
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBodyTest.java
Labels: enhancement 🕵️‍♀️

#592 Attestation criteria change
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: bug 🐞, enhancement 🕵️‍♀️

#593 Fixes build errors related from tests
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/ValidatorsUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockHeaderTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/ProposalTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/ProposerSlashingTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateWithCacheTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/ForkTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: enhancement 🕵️‍♀️, testing 💯🖍

#596 changed Dockerfile to openjdk
  docker/wb/Dockerfile
Labels: enhancement 🕵️‍♀️

#599 message_type attribute integration
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/AttestationUtil.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsSubProtocolHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipCodec.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipMessage.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/HobbitsSocketHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/MessageType.java
  networking/p2p/src/test/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipCodecTest.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
Labels: enhancement 🕵️‍♀️

#600 Message type part 2
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipCodec.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/HobbitsSocketHandler.java
Labels: bug 🐞

#601 Add date to JSON and CSV log output
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  data/adapter/src/main/java/tech/pegasys/artemis/data/adapter/TimeSeriesAdapter.java
  data/build.gradle
  data/provider/build.gradle
  data/provider/src/main/java/tech/pegasys/artemis/data/provider/CSVProvider.java
  data/provider/src/main/java/tech/pegasys/artemis/data/provider/FileProvider.java
  data/provider/src/main/java/tech/pegasys/artemis/data/provider/JSONProvider.java
  data/provider/src/test/java/tech/pegasys/artemis/data/provider/CSVProviderTest.java
  data/provider/src/test/java/tech/pegasys/artemis/data/provider/JSONProviderTest.java
  data/src/main/java/tech/pegasys/artemis/data/RawRecord.java
  data/src/main/java/tech/pegasys/artemis/data/TimeSeriesRecord.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipCodec.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/RPCCodec.java
  util/build.gradle
  util/src/main/java/tech/pegasys/artemis/util/json/BytesModule.java
Labels: enhancement 🕵️‍♀️

#550 Removes all usages of UnsignedLong usage and changes to long.
  data/adapter/src/main/java/tech/pegasys/artemis/data/adapter/TimeSeriesAdapter.java
  data/build.gradle
  data/src/main/java/tech/pegasys/artemis/data/TimeSeriesRecord.java
  data/src/main/java/tech/pegasys/artemis/data/ValidatorJoin.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Constants.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1DataVote.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Proposal.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Attestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Deposit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/ProposerSlashing.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/SlashableAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Transfer.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/VoluntaryExit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/BeaconState.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Crosslink.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/CrosslinkCommittee.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Fork.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/PendingAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Validator.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/AttestationUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/CrosslinkCommitteeUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/ValidatorsUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/Eth1DataVoteTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/ProposalTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/ProposerSlashingTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/SlashableAttestationTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/VoluntaryExitTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateWithCacheTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/CrosslinkTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/ForkTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/PendingAttestationTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/ValidatorTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtilTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/ValidatorsUtilTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/LmdGhost.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/SlotProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/StateTransitionTest.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
  services/powchain/src/main/java/tech/pegasys/artemis/services/powchain/PowchainService.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
  util/src/main/java/tech/pegasys/artemis/util/bitwise/BitwiseOps.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSVerify.java
  util/src/main/java/tech/pegasys/artemis/util/config/ArtemisConfiguration.java
  util/src/test/java/tech/pegasys/artemis/util/bitwise/BitwiseOpstTest.java
  validator/client/src/main/java/tech/pegasys/artemis/validator/client/Validator.java
  validator/client/src/main/java/tech/pegasys/artemis/validator/client/ValidatorClient.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: enhancement 🕵️‍♀️

#603 Fix constants to match 0.4
  config/config.toml
Labels: enhancement 🕵️‍♀️

#606 adding time attribute and fixing output issue
  artemis/src/main/java/tech/pegasys/artemis/Artemis.java
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  config/demoConfig.0.toml
  config/demoConfig.1.toml
  config/demoConfig.2.toml
  config/demoConfig.3.toml
  config/rlpxConfig.0.toml
  config/testConfig.0.toml
  config/testConfig.1.toml
  config/testConfig.2.toml
  data/src/main/java/tech/pegasys/artemis/data/TimeSeriesRecord.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipCodec.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/GossipMessage.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/HobbitsSocketHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/MessageType.java
Labels: enhancement 🕵️‍♀️

#608 int overflow fixes
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/SlotProcessorUtil.java
Labels: bug 🐞

#613 Fixed NullPointer error and removed rlpx
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  artemis/src/test/java/tech/pegasys/artemis/BeaconNodeIntegrationTest.java
  config/config.toml
  config/demoConfig.0.toml
  config/demoConfig.1.toml
  config/demoConfig.2.toml
  config/demoConfig.3.toml
  config/rlpxConfig.0.toml
  config/rlpxConfig.1.toml
  config/rlpxConfig.2.toml
  config/testConfig.0.toml
  config/testConfig.1.toml
  config/testConfig.2.toml
  data/adapter/src/main/java/tech/pegasys/artemis/data/adapter/TimeSeriesAdapter.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsSubProtocol.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsSubProtocolHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/RLPxP2PNetwork.java
  networking/p2p/src/test/java/tech/pegasys/artemis/networking/p2p/HobbitsSubProtocolTest.java
  util/src/main/java/tech/pegasys/artemis/util/cli/CommandLineArguments.java
Labels: bug 🐞, enhancement 🕵️‍♀️

#614 Fixes get_crosslink_committees_at_slot() logic and test
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtilTest.java
Labels: testing 💯🖍
