Repository Consensys/teku, pull requests merged in 2019-07, with the labels that each got.

#754 Remove SlashableAttestation from v0.7.1 of Artemis.
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/SlashableAttestation.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttesterSlashingTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/SlashableAttestationTest.java
Labels: code style 💅

#753 Make floodsub work
  artemis.env
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/AbstractSocketHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/FloodsubSocketHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/PlumtreeSocketHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/rpc/RPCMessage.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/rpc/RequestBlocksMessage.java
  scripts/run_utils.sh
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
Labels: enhancement 🕵️‍♀️

#762 Add Interop start mode
  README.md
  build.gradle
  config/config.toml
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  scripts/run_utils.sh
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSKeyPair.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSSecretKey.java
  util/src/main/java/tech/pegasys/artemis/util/config/ArtemisConfiguration.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: enhancement 🕵️‍♀️

#764 Clean memory after finalization
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/LmdGhost.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorage.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageServer.java
Labels: enhancement 🕵️‍♀️

#766 Add generated proto files to main sourceset
  build.gradle
Labels: bug 🐞

#756 Correctly Implement New SOS/SSZ Functionality
  build.gradle
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBody.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockHeader.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1Data.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1DataVote.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Attestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationDataAndCustodyBit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttesterSlashing.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Deposit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/IndexedAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/ProposerSlashing.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Transfer.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/VoluntaryExit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/BeaconState.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Crosslink.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Fork.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/HistoricalBatch.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/PendingAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/SimpleOffsetSerializer.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/FixedPartSSZSOSTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateWithCacheTest.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSPublicKey.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSSignature.java
  util/src/main/java/tech/pegasys/artemis/util/sos/SimpleOffsetSerializable.java
Labels: enhancement 🕵️‍♀️

#794 SSZ v0.8.1 - Merklize
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBody.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockHeader.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1Data.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Attestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/IndexedAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Transfer.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/VoluntaryExit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Checkpoint.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Crosslink.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Fork.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/HistoricalBatch.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Validator.java
  util/src/main/java/tech/pegasys/artemis/util/hashtree/HashTreeUtil.java
Labels: enhancement 🕵️‍♀️
