Repository Consensys/teku, pull requests merged in 2019-02, with the labels that each got.

#228 Implement ChainStorageService
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Constants.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBody.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Attestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Deposit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositInput.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Exit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/ProposerSlashing.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/SlashableVoteData.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositInputTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/BeaconState.java
  gradle/versions.gradle
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
  services/chainstorage/build.gradle
  services/chainstorage/src/main/java/tech/pegasys/artemis/services/chainstorage/ChainStorageService.java
  settings.gradle
  storage/build.gradle
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorage.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSVerify.java
Labels: enhancement 🕵️‍♀️, in progress 🚧

#232 Block processing 3b
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1DataVote.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/BeaconState.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#245 Use JDK11 for CI
  Jenkinsfile
Labels: enhancement 🕵️‍♀️

#251 state transition tests
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/SlotProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/StateTransitionTest.java
Labels: enhancement 🕵️‍♀️

#252 exit_validator test
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Constants.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/BeaconState.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/BeaconStateTest.java
Labels: enhancement 🕵️‍♀️

#254 Rename validator_registry_latest_change_slot
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/BeaconState.java
Labels: code style 💅

#258 Implement light client friendliness
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/ValidatorRegistryDeltaBlock.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/ValidatorRegistryDeltaBlockTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/BeaconState.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/BeaconStateTest.java
Labels: enhancement 🕵️‍♀️

#265 Remove shard committee from state
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/CrosslinkCommittee.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/BeaconState.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: in progress 🚧

#268 Chain Storage Integration
  ethereum/statetransition/build.gradle
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  services/chainstorage/src/main/java/tech/pegasys/artemis/services/chainstorage/ChainStorageService.java
  services/src/main/java/tech/pegasys/artemis/services/ServiceController.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorage.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageServer.java
Labels: enhancement 🕵️‍♀️

#269 Chain Storage Merge Fix
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
Labels: bug 🐞

#271 Implement SSZ and test round-trip for blocks and operations datastructures.
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBody.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1Data.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/ProposalSignedData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Attestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/CasperSlashing.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Deposit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositInput.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Exit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/ProposerSlashing.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/SlashableVoteData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBodyTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/Eth1DataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/ProposalSignedDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/CasperSlashingTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositInputTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/ExitTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/ProposerSlashingTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/SlashableVoteDataTest.java
  gradle/versions.gradle
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
Labels: enhancement 🕵️‍♀️

#273 Fix: UnsignedLong.valueOf to UnsignedLong.fromLongBits
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationData.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: bug 🐞

#277 Init state
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/BeaconState.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/SlotProcessorUtil.java
  pow/src/main/java/tech/pegasys/artemis/pow/ValidatorRegistrationClient.java
  services/beaconchain/src/main/java/tech/pegasys/artemis/services/beaconchain/BeaconChainService.java
  services/powchain/src/main/java/tech/pegasys/artemis/services/powchain/PowchainService.java
Labels: bug 🐞, enhancement 🕵️‍♀️

#280 update process_penalties_and_exits
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/ValidatorsUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtilTest.java
Labels: enhancement 🕵️‍♀️

#282 update process_ejections
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#284 updated update_validator_registry
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#287 Changing BeaconState.java fields to use List instead of ArrayList #233
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/BeaconState.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/SlotProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/StateTransitionTest.java
Labels: code style 💅

#288 Fixes made to make finalBookKeepingTests work
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Validator.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
Labels: enhancement 🕵️‍♀️

#293 RemoveBalance from Validator
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/CrosslinkCommittee.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Validator.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Validators.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/BeaconState.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/CrosslinkCommitteeUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/TreeHashUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/ValidatorsUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/BeaconStateTest.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/StateTransitionTest.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
Labels: enhancement 🕵️‍♀️

#286 Updates data structures to spec
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBody.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1Data.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/ProposalSignedData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Attestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationDataAndCustodyBit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttesterSlashing.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/CasperSlashing.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Deposit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Exit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/LatestBlockRoots.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/ProofOfCustodyChallenge.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/ProofOfCustodyResponse.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/ProofOfCustodySeedChange.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/SlashableAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Crosslink.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/CrosslinkRecord.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBodyTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/Eth1DataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/ProposalSignedDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttesterSlashingTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/BLSSignatureTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/CasperSlashingTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositInputTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/ExitTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/ProposerSlashingTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/SlashableAttestationTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/SlashableVoteDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/CrosslinkTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/BeaconState.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/BeaconStateTest.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
Labels: enhancement 🕵️‍♀️, in progress 🚧

#302 Implement update justification for per-Epoch Processing
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  util/src/main/java/tech/pegasys/artemis/util/bitwise/BitwiseOps.java
  util/src/test/java/tech/pegasys/artemis/util/bitwise/BitwiseOpstTest.java
Labels: in progress 🚧

#306 UpdateCrosslinks
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/BeaconStateTest.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
Labels: enhancement 🕵️‍♀️, in progress 🚧

#309 Implement and Test SSZ for Remaining Data Structures
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1DataVote.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationDataAndCustodyBit.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositInput.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Fork.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/PendingAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Validator.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBodyTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/Eth1DataVoteTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationDataAndCustodyBitTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttesterSlashingTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/SlashableAttestationTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/ForkTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/PendingAttestationTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/ValidatorTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/BeaconState.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
Labels: enhancement 🕵️‍♀️

#315 Remove ShardReassignmentRecord to Comply with Spec
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/ShardReassignmentRecord.java
Labels: code style 💅, in progress 🚧

#316 Fixes field latest_crosslink to latest_crosslink_root
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationDataTest.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/BeaconStateTest.java
Labels: code style 💅

#318 Change remaining Bytes48 Lists to BLSSignature.
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockTest.java
Labels: code style 💅, enhancement 🕵️‍♀️

#321 Preconditions and Minor epoch reorg
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: code style 💅, enhancement 🕵️‍♀️

#322 reward and penalty helper functions
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtilTest.java
Labels: enhancement 🕵️‍♀️

#328 implement rewardsAndPenalties(): Justification and Finalization
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/ValidatorsUtil.java
Labels: enhancement 🕵️‍♀️

#326 Update Deposit Helper Functions to v0.1
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtilTest.java
Labels: enhancement 🕵️‍♀️, in progress 🚧

#332 implement rewardsAndPenalties(): attestation inclusion
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#331 Penalties cleanup
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Validator.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/ValidatorsUtil.java
Labels: enhancement 🕵️‍♀️

#333 implement rewardsAndPenalties: crosslinkRewards()
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#335 Update eth1 data
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#336 implement finalUpdates()
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#341 Epoch Processing Finished
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/TreeHashUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
Labels: enhancement 🕵️‍♀️

#348 Implement penalize_validator helper methods for block processing.
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Validator.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtilTest.java
Labels: enhancement 🕵️‍♀️

#345 fixes related to runtime errors
  artemis/src/main/java/tech/pegasys/artemis/Artemis.java
  build.gradle
  ethereum/datastructures/src/main/java/resources/log4j2.xml
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/test/resources/log4j2.xml
  ethereum/statetransition/src/main/java/resources/log4j2.xml
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/BeaconState.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/SlotProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/TreeHashUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/BeaconStateTest.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/StateTransitionTest.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
  ethereum/statetransition/src/test/resources/log4j2.xml
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
  services/adapter/src/test/java/tech/pegasys/artemis/services/adapter/ServiceAdapterTest.java
  services/adapter/src/test/resources/log4j2.xml
  services/beaconnode/src/main/java/tech/pegasys/artemis/services/beaconnode/BeaconNodeService.java
  services/chainstorage/src/main/java/tech/pegasys/artemis/services/chainstorage/ChainStorageService.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorage.java
Labels: bug 🐞

#352 Adding cli option to set the logging level
  artemis/src/main/java/tech/pegasys/artemis/Artemis.java
  util/build.gradle
  util/src/main/java/tech/pegasys/artemis/util/cli/CommandLineArguments.java
Labels: enhancement 🕵️‍♀️

#356 attestationutils helper method and hash_tree_root(List<Validator> validators)
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/TreeHashUtil.java
Labels: code style 💅

#350 Block process util operation functions
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/PendingAttestation.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/PendingAttestationTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/TreeHashUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/BeaconStateTest.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSVerify.java
Labels: enhancement 🕵️‍♀️

#351 Epoch processing last helpers
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: in progress 🚧

#364 OnChainStart -> SlotScheduling
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  services/beaconchain/src/main/java/tech/pegasys/artemis/services/beaconchain/BeaconChainService.java
Labels: enhancement 🕵️‍♀️

#371 Add Integer List Support to TreeHashUtil
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/TreeHashUtil.java
Labels: enhancement 🕵️‍♀️

#369 Finalize Block Processing AND Add to State Transition
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Constants.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#376 Framework Modification needed for ChainStore
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/BeaconState.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/AttestationUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/CrosslinkCommitteeUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/InterfaceAdapter.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/ValidatorsUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtilTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/ValidatorsUtilTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/SlotProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/StateTransitionTest.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorage.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageServer.java
  util/src/main/java/tech/pegasys/artemis/util/hashtree/HashTreeUtil.java
Labels: enhancement 🕵️‍♀️

#383 BLSException type and temporary trap
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSException.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSSignature.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSVerify.java
  util/src/test/java/tech/pegasys/artemis/util/bls/BLSSignatureTest.java
Labels: enhancement 🕵️‍♀️

#382 basic simulation
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessingException.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessingException.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/SlotProcessingException.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorage.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageServer.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSSignature.java
  util/src/main/java/tech/pegasys/artemis/util/mikuli/KeyPair.java
  util/src/main/java/tech/pegasys/artemis/util/mikuli/Signature.java
Labels: enhancement 🕵️‍♀️

#400 The happiest path
  artemis/src/main/resources/log4j2.xml
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
Labels: enhancement 🕵️‍♀️

#402 happy path part 2
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
Labels: enhancement 🕵️‍♀️

#393 Adding epoch to the hash calculation in generate_seed
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateTest.java
Labels: enhancement 🕵️‍♀️

#399 Add latest_crosslink to AttestationData
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/AttestationData.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#405 Fix bounds checking in verify_bitfield - (Spec PR #573)
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
Labels: enhancement 🕵️‍♀️

#407 bug in happy path
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
Labels: bug 🐞
