Repository Consensys/teku, pull requests merged in 2019-03, with the labels that each got.

#412 state root verification failure fix
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
Labels: bug 🐞

#408 Verify logic in update_eth1_data matches the spec - (Spec PR #561)
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#415 Cli logging fix
  Jenkinsfile
  README.md
  artemis/src/main/java/tech/pegasys/artemis/Artemis.java
  util/src/main/java/tech/pegasys/artemis/util/cli/CommandLineArguments.java
  util/src/main/java/tech/pegasys/artemis/util/cli/LogTypeConverter.java
Labels: bug 🐞

#417 Refactor point serialisation and improve testing
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSPublicKey.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSSignature.java
  util/src/main/java/tech/pegasys/artemis/util/mikuli/BLS12381.java
  util/src/main/java/tech/pegasys/artemis/util/mikuli/G1Point.java
  util/src/main/java/tech/pegasys/artemis/util/mikuli/G2Point.java
  util/src/main/java/tech/pegasys/artemis/util/mikuli/PublicKey.java
  util/src/main/java/tech/pegasys/artemis/util/mikuli/Signature.java
  util/src/test/java/tech/pegasys/artemis/util/mikuli/G1PointTest.java
  util/src/test/java/tech/pegasys/artemis/util/mikuli/G2PointTest.java
Labels: enhancement 🕵️‍♀️

#419 Simulated Data bug fixes
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  networking/p2p/build.gradle
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSVerify.java
Labels: bug 🐞, in progress 🚧

#422 Fix get set justified block&state
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
Labels: enhancement 🕵️‍♀️

#413 Add Support for Transfers Between Withdrawn Accounts - (Spec PR #601)
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Constants.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlock.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBody.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Transfer.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBodyTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSPublicKey.java
Labels: enhancement 🕵️‍♀️, in progress 🚧

#424 Fixes build errors.
  Jenkinsfile
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: code style 💅

#426 Implements get_committee_assignment for validator assignment
  validatorclient/src/main/java/tech/pegasys/artemis/validatorclient/CommitteeAssignmentTuple.java
  validatorclient/src/main/java/tech/pegasys/artemis/validatorclient/ValidatorClient.java
Labels: enhancement 🕵️‍♀️

#428 Update constant names and fields to v0.4
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Constants.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  services/beaconchain/src/main/java/tech/pegasys/artemis/services/beaconchain/BeaconChainService.java
Labels: code style 💅

#423 Block Proposal with ForkChoice and Deterministic Signatures
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSKeyPair.java
  util/src/main/java/tech/pegasys/artemis/util/bls/BLSVerify.java
  util/src/test/java/tech/pegasys/artemis/util/bls/BLSSignatureTest.java
Labels: enhancement 🕵️‍♀️

#429 Fix verifyRandao failure in demo
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
Labels: bug 🐞

#431 Cleanup StateTreeManager
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  services/beaconchain/src/main/java/tech/pegasys/artemis/services/beaconchain/BeaconChainService.java
Labels: code style 💅

#432 Change bitfields to use variable length Bytes.
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Attestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/SlashableAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/PendingAttestation.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockBodyTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/BeaconBlockTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/Eth1DataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/Eth1DataVoteTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/blocks/ProposalSignedDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationDataAndCustodyBitTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttestationTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/AttesterSlashingTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositDataTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositInputTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/DepositTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/ExitTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/ProposerSlashingTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/operations/SlashableAttestationTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/CrosslinkTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/ForkTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/PendingAttestationTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/ValidatorTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
Labels: enhancement 🕵️‍♀️, in progress 🚧

#420 Implement swap-or-not-shuffle
  eth-reference-tests/build.gradle
  eth-reference-tests/src/test/java/pegasys/artemis/reference/PermutedIndexTestSuite.java
  eth-reference-tests/src/test/resources/eth2.0-tests_tmp/test_vector_permutated_index_tmp.yml
  eth-reference-tests/src/test/resources/log4j2.xml
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtilTest.java
Labels: enhancement 🕵️‍♀️

#435 Update to latest (pre-release) official BLS tests
  eth-reference-tests/src/test/java/pegasys/artemis/reference/BLSTestSuite.java
  eth-reference-tests/src/test/resources/eth2.0-tests_tmp/test_bls_tmp.yml
Labels: enhancement 🕵️‍♀️

#437 Bring get_previous_epoch() up to 0.4 spec
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtilTest.java
Labels: enhancement 🕵️‍♀️

#442 Adds ALogger wrapper class and adds demo print flag
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  gradle/wrapper/gradle-wrapper.properties
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
  pow/build.gradle
  pow/src/main/java/tech/pegasys/artemis/ganache/GanacheController.java
  pow/src/main/java/tech/pegasys/artemis/pow/DepositContractListenerFactory.java
  services/beaconnode/build.gradle
  services/beaconnode/src/main/java/tech/pegasys/artemis/services/beaconnode/BeaconNodeService.java
  services/chainstorage/build.gradle
  services/chainstorage/src/main/java/tech/pegasys/artemis/services/chainstorage/ChainStorageService.java
  services/powchain/build.gradle
  services/powchain/src/main/java/tech/pegasys/artemis/services/powchain/PowchainService.java
  storage/build.gradle
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorage.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageServer.java
  util/src/main/java/tech/pegasys/artemis/util/alogger/ALogger.java
Labels: enhancement 🕵️‍♀️

#439 Update to get_next_epoch()
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtilTest.java
Labels: enhancement 🕵️‍♀️

#445 data adapter/provider functionality
  .gitignore
  README.md
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  data/provider/src/main/java/tech/pegasys/artemis/data/provider/CSVProvider.java
  data/provider/src/main/java/tech/pegasys/artemis/data/provider/FileProvider.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
  util/src/main/java/tech/pegasys/artemis/util/cli/CommandLineArguments.java
Labels: enhancement 🕵️‍♀️

#451 Epoch fix
  README.md
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  data/adapter/src/main/java/tech/pegasys/artemis/data/adapter/TimeSeriesAdapter.java
  data/provider/build.gradle
  data/provider/src/main/java/tech/pegasys/artemis/data/provider/ProviderTypes.java
  data/src/main/java/tech/pegasys/artemis/data/RawRecord.java
  data/src/main/java/tech/pegasys/artemis/data/TimeSeriesRecord.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/SlotProcessorUtil.java
  gradle/versions.gradle
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
  util/src/main/java/tech/pegasys/artemis/util/cli/CommandLineArguments.java
Labels: enhancement 🕵️‍♀️

#433 Update total_balance to get_total_balance.
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/AttestationUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtilTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
Labels: enhancement 🕵️‍♀️

#453 Bugfix: fix remaining referenece to Bytes32 bitfields
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
Labels: bug 🐞

#456 Update get_bitfield_bit logic to have little endian bit numbering.
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
Labels: enhancement 🕵️‍♀️

#458 Generate Flow Diagram
  README.md
  build.gradle
Labels: enhancement 🕵️‍♀️

#460 cleanup
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  services/beaconnode/build.gradle
  services/beaconnode/src/main/java/tech/pegasys/artemis/services/beaconnode/BeaconNodeService.java
Labels: code style 💅

#462 Validator Coordinator
  artemis/build.gradle
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/MockP2PNetwork.java
  settings.gradle
  storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageClient.java
  util/src/main/java/tech/pegasys/artemis/util/alogger/ALogger.java
  validator/build.gradle
  validator/client/build.gradle
  validator/client/src/main/java/tech/pegasys/artemis/validator/client/CommitteeAssignmentTuple.java
  validator/client/src/main/java/tech/pegasys/artemis/validator/client/ValidatorClient.java
  validator/coordinator/build.gradle
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: enhancement 🕵️‍♀️

#466 Fix constants and affected function
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Constants.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#495 Improved StateTransition exception handling
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/AttestationUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessingException.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessingException.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/SlotProcessorUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/artemis/statetransition/util/EpochProcessingUtilTest.java
Labels: enhancement 🕵️‍♀️

#496 Fixes comment in processAttestations
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
Labels: documentation :memo:

#463 Validator Coordinator Mods, TOML config, and RLPx Network
  artemis/build.gradle
  artemis/src/main/java/tech/pegasys/artemis/ArtemisConfiguration.java
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  config/config.toml
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/statetransition/build.gradle
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  gradle/versions.gradle
  networking/p2p/build.gradle
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/BeaconSubprotocol.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/BeaconSubprotocolHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/PingMessage.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/RLPxP2PNetwork.java
  networking/p2p/src/test/java/tech/pegasys/artemis/networking/p2p/BeaconSubprotocolHandlerTest.java
  networking/p2p/src/test/java/tech/pegasys/artemis/networking/p2p/BeaconSubprotocolTest.java
  services/adapter/build.gradle
  services/adapter/src/main/java/tech/pegasys/artemis/services/adapter/ServiceAdapter.java
  services/adapter/src/test/java/tech/pegasys/artemis/services/adapter/ServiceAdapterTest.java
  services/beaconchain/build.gradle
  services/beaconchain/src/main/java/tech/pegasys/artemis/services/beaconchain/BeaconChainService.java
  services/build.gradle
  services/chainstorage/build.gradle
  services/chainstorage/src/main/java/tech/pegasys/artemis/services/chainstorage/ChainStorageService.java
  services/powchain/build.gradle
  services/powchain/src/main/java/tech/pegasys/artemis/services/powchain/PowchainService.java
  services/src/main/java/tech/pegasys/artemis/services/ServiceConfig.java
  services/src/main/java/tech/pegasys/artemis/services/ServiceController.java
  services/src/main/java/tech/pegasys/artemis/services/ServiceInterface.java
  util/src/main/java/tech/pegasys/artemis/util/cli/CommandLineArguments.java
  validator/coordinator/build.gradle
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: enhancement 🕵️‍♀️

#497 Clarify and Fix How Attestation Rewards are Handled
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/AttestationUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: enhancement 🕵️‍♀️, in progress 🚧

#501 Demo attestations
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/Attestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/BeaconState.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/PendingAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/AttestationUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTransition.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
  services/beaconchain/src/main/java/tech/pegasys/artemis/services/beaconchain/BeaconChainService.java
  util/src/main/java/tech/pegasys/artemis/util/mikuli/PublicKey.java
  util/src/main/java/tech/pegasys/artemis/util/mikuli/Signature.java
  util/src/test/java/tech/pegasys/artemis/util/mikuli/PublicKeyTest.java
  util/src/test/java/tech/pegasys/artemis/util/mikuli/SignatureTest.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: enhancement 🕵️‍♀️

#506 Add hobbits p2p network
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  util/src/main/java/tech/pegasys/artemis/util/config/ArtemisConfiguration.java
  util/src/test/java/tech/pegasys/artemis/util/config/ArtemisConfigurationTest.java
Labels: enhancement 🕵️‍♀️

#509 config fix
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java
Labels: bug 🐞

#510 off by one error
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
Labels: bug 🐞

#512 Add hobbits p2p hello, status, goodbye messages
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  networking/p2p/build.gradle
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/GetStatus.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/Hello.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/HobbitsSocketHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/Peer.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/RPCCodec.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/RPCMessage.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/RPCMethod.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/package-info.java
  networking/p2p/src/test/java/tech/pegasys/artemis/networking/p2p/hobbits/JsonRoundtripTest.java
  networking/p2p/src/test/java/tech/pegasys/artemis/networking/p2p/hobbits/RPCCodecTest.java
Labels: enhancement 🕵️‍♀️

#513 Add integration test to ensure 3 Artemis nodes can communicate
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  artemis/src/test/java/tech/pegasys/artemis/BeaconNodeIntegrationTest.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/HobbitsSocketHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/RPCCodec.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/RPCMessage.java
Labels: enhancement 🕵️‍♀️

#516 Fixes a Couple of Things Noticed While Reviewing Previous PR
  data/adapter/build.gradle
  data/provider/build.gradle
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Constants.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/ValidatorsUtil.java
  ethereum/statetransition/build.gradle
Labels: enhancement 🕵️‍♀️

#517 Fix Some Synchronization Pitfalls
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/ValidatorsUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: bug 🐞

#519 Preserve Constants Vals for Testing
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Constants.java
Labels: bug 🐞

#520 Deep copy
  config/config.toml
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Copyable.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/blocks/Eth1DataVote.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/BeaconStateWithCache.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Crosslink.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/PendingAttestation.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/Validator.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/ValidatorsUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/state/BeaconStateWithCacheTest.java
Labels: bug 🐞, enhancement 🕵️‍♀️

#511 Double Check v0.4 Update, Make Final Changes
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Constants.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/operations/DepositInput.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/state/BeaconState.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/DataStructureUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtilTest.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/EpochProcessorUtil.java
Labels: enhancement 🕵️‍♀️

#528 Add additional RPC methods and data structures
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/HobbitsP2PNetwork.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/BlockBodies.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/BlockHeaders.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/BlockRoots.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/HobbitsSocketHandler.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/RPCCodec.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/RPCMethod.java
  networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/hobbits/RequestBlocks.java
  networking/p2p/src/test/java/tech/pegasys/artemis/networking/p2p/hobbits/JsonRoundtripTest.java
Labels: enhancement 🕵️‍♀️

#530 fixed help menu null reference error
  README.md
  services/src/main/java/tech/pegasys/artemis/services/ServiceController.java
Labels: bug 🐞

#533 Add Execution Test to CI Pipeline
  Jenkinsfile
  artemis/src/main/resources/artemisTestScript.sh
Labels: enhancement 🕵️‍♀️

#534 Override constants
  artemis/src/main/java/tech/pegasys/artemis/BeaconNode.java
  config/config.toml
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/Constants.java
  ethereum/datastructures/src/main/java/tech/pegasys/artemis/datastructures/util/BeaconStateUtil.java
  ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/util/BlockProcessorUtil.java
  util/src/main/java/tech/pegasys/artemis/util/config/ArtemisConfiguration.java
Labels: enhancement 🕵️‍♀️, testing 💯🖍
