Repository Consensys/teku, pull requests merged in 2020-12, with the labels that each got.

#3346 Make eth1 max block range for requesting deposit event logs configurable
  pow/src/main/java/tech/pegasys/teku/pow/DepositFetcher.java
  pow/src/test/java/tech/pegasys/teku/pow/DepositsFetcherTest.java
  services/powchain/src/main/java/tech/pegasys/teku/services/powchain/PowchainService.java
  teku/src/main/java/tech/pegasys/teku/cli/BeaconNodeCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/options/DepositOptions.java
  teku/src/test/java/tech/pegasys/teku/cli/BeaconNodeCommandTest.java
  util/src/main/java/tech/pegasys/teku/util/config/GlobalConfiguration.java
  util/src/main/java/tech/pegasys/teku/util/config/GlobalConfigurationBuilder.java
Labels: documentation :memo:

#3358 default the epoch for the voluntary-exit command to current epoch
  ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/validation/VoluntaryExitValidator.java
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/VoluntaryExitCommand.java
  validator/remote/src/main/java/tech/pegasys/teku/validator/remote/apiclient/OkHttpValidatorRestApiClient.java
  validator/remote/src/main/java/tech/pegasys/teku/validator/remote/apiclient/ValidatorApiMethod.java
Labels: documentation :memo:

#3370 External signer upcheck
  infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/StatusLogger.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/loader/ValidatorLoader.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/ExternalSignerStatusLogger.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/ExternalSignerUpcheck.java
  validator/client/src/test/java/tech/pegasys/teku/validator/client/loader/ValidatorLoaderTest.java
  validator/client/src/test/java/tech/pegasys/teku/validator/client/signer/ExternalSignerStatusLoggerTest.java
Labels: TeamGroot

#3250 TLS configuration for external signer
  teku/src/main/java/tech/pegasys/teku/cli/options/ValidatorKeysOptions.java
  teku/src/test/java/tech/pegasys/teku/cli/BeaconNodeCommandTest.java
  teku/src/test/java/tech/pegasys/teku/cli/options/ValidatorOptionsTest.java
  validator/api/src/main/java/tech/pegasys/teku/validator/api/ValidatorConfig.java
  validator/api/src/test/java/tech/pegasys/teku/validator/api/ValidatorConfigTest.java
  validator/client/src/integration-test/java/tech/pegasys/teku/validator/client/signer/ExternalSignerIntegrationTest.java
  validator/client/src/integration-test/java/tech/pegasys/teku/validator/client/signer/ExternalSignerUpcheckTLSIntegrationTest.java
  validator/client/src/integration-test/resources/mockito_truststore.p12
  validator/client/src/integration-test/resources/pass.txt
  validator/client/src/integration-test/resources/teku_client.pem
  validator/client/src/integration-test/resources/teku_client_keystore.p12
  validator/client/src/main/java/tech/pegasys/teku/validator/client/loader/HttpClientExternalSignerFactory.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/loader/ValidatorLoader.java
  validator/client/src/test/java/tech/pegasys/teku/validator/client/loader/ValidatorLoaderTest.java
Labels: TeamGroot, documentation :memo:

#3347 Heap optimize: reduce BeaconState.Validators backing tree memory consumption
  ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/state/BeaconState.java
  ssz/src/main/java/tech/pegasys/teku/ssz/backing/tree/LeafDataNode.java
  ssz/src/main/java/tech/pegasys/teku/ssz/backing/tree/LeafNode.java
  ssz/src/main/java/tech/pegasys/teku/ssz/backing/tree/SszNodeTemplate.java
  ssz/src/main/java/tech/pegasys/teku/ssz/backing/tree/SszSuperNode.java
  ssz/src/main/java/tech/pegasys/teku/ssz/backing/tree/TreeNodeImpl.java
  ssz/src/main/java/tech/pegasys/teku/ssz/backing/tree/TreeUpdates.java
  ssz/src/main/java/tech/pegasys/teku/ssz/backing/tree/TreeUtil.java
  ssz/src/main/java/tech/pegasys/teku/ssz/backing/type/CollectionViewType.java
  ssz/src/main/java/tech/pegasys/teku/ssz/backing/type/ListViewType.java
  ssz/src/main/java/tech/pegasys/teku/ssz/backing/type/TypeHints.java
  ssz/src/main/java/tech/pegasys/teku/ssz/backing/type/VectorViewType.java
  ssz/src/main/java/tech/pegasys/teku/ssz/backing/view/ListViewReadImpl.java
  ssz/src/main/java/tech/pegasys/teku/ssz/backing/view/VectorViewReadImpl.java
  ssz/src/test/java/tech/pegasys/teku/ssz/TestUtil.java
  ssz/src/test/java/tech/pegasys/teku/ssz/backing/ListViewHintsTest.java
  ssz/src/test/java/tech/pegasys/teku/ssz/backing/ListViewTest.java
  ssz/src/test/java/tech/pegasys/teku/ssz/backing/TestContainers.java
  ssz/src/test/java/tech/pegasys/teku/ssz/backing/tree/TreeUpdatesTest.java
Labels: performance 🚀

#3405 Publish all docker variants
  CHANGELOG.md
  build.gradle
Labels: documentation :memo:
