Repository Consensys/teku, pull requests merged in 2020-11, with the labels that each got.

#3156 Remove spadina and zinken networks
  teku/src/test/java/tech/pegasys/teku/cli/options/NetworkOptionsTest.java
  util/src/main/java/tech/pegasys/teku/util/config/Constants.java
  util/src/main/java/tech/pegasys/teku/util/config/NetworkDefinition.java
  util/src/main/resources/tech/pegasys/teku/util/config/spadina-genesis.ssz
  util/src/main/resources/tech/pegasys/teku/util/config/spadina.yaml
  util/src/main/resources/tech/pegasys/teku/util/config/zinken-genesis.ssz
  util/src/main/resources/tech/pegasys/teku/util/config/zinken.yaml
Labels: documentation :memo:

#3139 Enable different modes for performance tracking
  services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java
  teku/src/main/java/tech/pegasys/teku/cli/options/ValidatorOptions.java
  teku/src/test/java/tech/pegasys/teku/cli/BeaconNodeCommandTest.java
  teku/src/test/java/tech/pegasys/teku/cli/options/ValidatorOptionsTest.java
  util/src/main/java/tech/pegasys/teku/util/config/ValidatorPerformanceTrackingMode.java
  validator/api/src/main/java/tech/pegasys/teku/validator/api/ValidatorConfig.java
  validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/performance/DefaultPerformanceTracker.java
  validator/coordinator/src/test/java/tech/pegasys/teku/validator/coordinator/performance/DefaultPerformanceTrackerTest.java
Labels: documentation :memo:

#3191 External signer response content type
  validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/ExternalSigner.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/SigningResponseBody.java
Labels: TeamGroot

#3190 New versioning scheme
  .circleci/config.yml
  build.gradle
  gradle.properties
Labels: documentation :memo:

#3198 moved `/admin/log_level` to `/teku/v1/admin/log_level`
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/admin/PutLogLevel.java
Labels: documentation :memo:

#3202 Add CLI option to disable built-in slashing protection for external signers
  teku/src/main/java/tech/pegasys/teku/cli/options/ValidatorOptions.java
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/VoluntaryExitCommand.java
  teku/src/test/java/tech/pegasys/teku/cli/options/ValidatorOptionsTest.java
  validator/api/src/main/java/tech/pegasys/teku/validator/api/ValidatorConfig.java
  validator/client/src/integration-test/java/tech/pegasys/teku/validator/client/ExternalSignerIntegrationTest.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/ValidatorClientService.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/loader/ValidatorLoader.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/ExternalSigner.java
  validator/client/src/test/java/tech/pegasys/teku/validator/client/loader/ValidatorLoaderTest.java
Labels: documentation :memo:

#3208 make voluntary exit CLI visible.
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/VoluntaryExitCommand.java
Labels: documentation :memo:

#3229 Handle external signer refusal to sign due to violation of slashing conditions
  infrastructure/http/src/main/java/tech/pegasys/teku/infrastructure/http/HttpStatusCodes.java
  validator/client/build.gradle
  validator/client/src/integration-test/java/tech/pegasys/teku/validator/client/signer/ExternalSignerIntegrationTest.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/ExternalSigner.java
Labels: TeamGroot

#3238 Switch default network to MainNet
  teku/src/main/java/tech/pegasys/teku/cli/options/NetworkOptions.java
  teku/src/test/java/tech/pegasys/teku/cli/BeaconNodeCommandTest.java
Labels: documentation :memo:

#3220 [Issue-3063] Merge initial state options
  ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/state/AnchorPoint.java
  infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/StatusLogger.java
  services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java
  services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/WeakSubjectivityInitializer.java
  services/beaconchain/src/test/java/tech/pegasys/teku/services/beaconchain/WeakSubjectivityInitializerTest.java
  teku/src/main/java/tech/pegasys/teku/cli/BeaconNodeCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/converter/NetworkDefinitionConverter.java
  teku/src/main/java/tech/pegasys/teku/cli/options/NetworkOptions.java
  teku/src/main/java/tech/pegasys/teku/cli/options/WeakSubjectivityOptions.java
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/TransitionCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/ValidatorClientCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/admin/WeakSubjectivityCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/debug/DebugDbCommand.java
  teku/src/test/java/tech/pegasys/teku/cli/options/NetworkOptionsTest.java
  teku/src/test/java/tech/pegasys/teku/cli/options/WeakSubjectivityOptionsTest.java
  util/src/main/java/tech/pegasys/teku/util/config/GlobalConfiguration.java
  util/src/main/java/tech/pegasys/teku/util/config/GlobalConfigurationBuilder.java
Labels: documentation :memo:

#3318 initial-state should not be a hidden option.
  teku/src/main/java/tech/pegasys/teku/cli/options/WeakSubjectivityOptions.java
Labels: documentation :memo:

#3314 Use ValidatorsUtil.getValidatorPubKey where possible
  data/serializer/src/main/java/tech/pegasys/teku/api/schema/Validator.java
  data/serializer/src/main/java/tech/pegasys/teku/api/schema/ValidatorWithIndex.java
  data/serializer/src/test/java/tech/pegasys/teku/api/response/v1/beacon/ValidatorResponseTest.java
  ethereum/core/src/main/java/tech/pegasys/teku/core/BlockProcessorUtil.java
  ethereum/core/src/main/java/tech/pegasys/teku/core/blockvalidator/SimpleBlockValidator.java
  ethereum/core/src/main/java/tech/pegasys/teku/core/operationsignatureverifiers/ProposerSlashingSignatureVerifier.java
  ethereum/core/src/main/java/tech/pegasys/teku/core/operationsignatureverifiers/VoluntaryExitSignatureVerifier.java
  ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/state/Validator.java
  ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/util/BeaconStateUtil.java
  ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/util/LengthBoundCalculator.java
  ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/util/SimpleOffsetSerializer.java
  ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/util/ValidatorsUtil.java
  ethereum/datastructures/src/test/java/tech/pegasys/teku/datastructures/state/ValidatorTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/teku/datastructures/util/BeaconStateUtilTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/teku/datastructures/util/GenesisGeneratorTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/teku/datastructures/util/MockStartBeaconStateGeneratorTest.java
  ethereum/datastructures/src/test/java/tech/pegasys/teku/datastructures/util/ValidatorsUtilTest.java
  ethereum/datastructures/src/testFixtures/java/tech/pegasys/teku/datastructures/util/DataStructureUtil.java
  ethereum/statetransition/src/test/java/tech/pegasys/teku/statetransition/util/BlockProcessorUtilTest.java
  services/beaconchain/src/test/java/tech/pegasys/teku/services/beaconchain/BeaconChainMetricsTest.java
  validator/client/src/test/java/tech/pegasys/teku/validator/client/duties/DutyResultTest.java
  validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandler.java
  validator/coordinator/src/test/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandlerTest.java
Labels: optimization 🚀

#3315 Optimize ValidatorsUtil.getValidatorIndex
  ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/util/ValidatorsUtil.java
Labels: optimization 🚀

#3322 Add support for Cors Origin requests on the Beacon Node Rest API
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/AbstractDataBackedRestAPIIntegrationTest.java
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/beacon/RestApiHostAllowlistIntegrationTest.java
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/BeaconRestApi.java
  teku/src/main/java/tech/pegasys/teku/cli/BeaconNodeCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/options/BeaconRestApiOptions.java
  teku/src/test/java/tech/pegasys/teku/cli/BeaconNodeCommandTest.java
  teku/src/test/java/tech/pegasys/teku/cli/options/BeaconRestApiOptionsTest.java
  teku/src/test/resources/beaconRestApiOptions_config.yaml
  util/src/main/java/tech/pegasys/teku/util/config/GlobalConfiguration.java
  util/src/main/java/tech/pegasys/teku/util/config/GlobalConfigurationBuilder.java
Labels: bug 🐞, documentation :memo:

#3330 Update the description of eth1-deposit-contract-address
  teku/src/main/java/tech/pegasys/teku/cli/options/DepositOptions.java
Labels: documentation :memo:
