Repository Consensys/teku, pull requests merged in 2020-06, with the labels that each got.

#2029 ForbiddenResponse if host not on whitelist
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/AbstractDataBackedRestAPIIntegrationTest.java
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/beacon/RestApiHostWhitelistIntegrationTest.java
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/BeaconRestApi.java
  data/beaconrestapi/src/test/java/tech/pegasys/teku/beaconrestapi/BeaconRestApiTest.java
Labels: TeamZiz

#2051 [MINOR] make whitelists configs obvious
  config/config.yaml
Labels: TeamZiz

#2045 load eth1 deposits from storage on startup
  pow/build.gradle
  pow/src/main/java/tech/pegasys/teku/pow/DepositProcessingController.java
  pow/src/main/java/tech/pegasys/teku/pow/Eth1DepositManager.java
  services/chainstorage/src/main/java/tech/pegasys/teku/services/chainstorage/StorageService.java
  services/powchain/build.gradle
  services/powchain/src/main/java/tech/pegasys/teku/services/powchain/PowchainService.java
  storage/api/build.gradle
  storage/api/src/main/java/tech/pegasys/teku/storage/api/schema/ReplayDepositsResult.java
  storage/src/main/java/tech/pegasys/teku/storage/api/FinalizedCheckpointChannel.java
  storage/src/main/java/tech/pegasys/teku/storage/api/StorageQueryChannel.java
  storage/src/main/java/tech/pegasys/teku/storage/server/DepositStorage.java
  storage/src/test/java/tech/pegasys/teku/storage/server/DepositStorageTest.java
  teku/src/main/java/tech/pegasys/teku/cli/BeaconNodeCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/options/DepositOptions.java
  teku/src/test/java/tech/pegasys/teku/cli/options/DepositOptionsTest.java
  teku/src/test/resources/depositOptions_config.yaml
  util/src/main/java/tech/pegasys/teku/util/config/TekuConfiguration.java
  util/src/main/java/tech/pegasys/teku/util/config/TekuConfigurationBuilder.java
Labels: TeamZiz

#2076 Add graffiti parameter to GetNewBlock
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/validator/GetNewBlockDataBackedIntegrationTest.java
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/RestApiConstants.java
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/validator/GetNewBlock.java
  data/beaconrestapi/src/test/java/tech/pegasys/teku/beaconrestapi/handlers/validator/GetNewBlockTest.java
  data/provider/src/main/java/tech/pegasys/teku/api/ValidatorDataProvider.java
  data/provider/src/test/java/tech/pegasys/teku/api/ValidatorDataProviderTest.java
  validator/api/src/main/java/tech/pegasys/teku/validator/api/ValidatorApiChannel.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/duties/BlockProductionDuty.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/metrics/MetricRecordingValidatorApiChannel.java
  validator/client/src/test/java/tech/pegasys/teku/validator/client/duties/BlockProductionDutyTest.java
  validator/client/src/test/java/tech/pegasys/teku/validator/client/metrics/MetricRecordingValidatorApiChannelTest.java
  validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockFactory.java
  validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandler.java
  validator/coordinator/src/test/java/tech/pegasys/teku/validator/coordinator/BlockFactoryTest.java
  validator/coordinator/src/test/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandlerTest.java
Labels: TeamZiz

#2085 [MINOR] improve genesis mock subcommand help (Default: stdout)
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/GenesisCommand.java
Labels: TeamZiz

#2090 replay deposits from storage by default.
  CHANGELOG.md
  teku/src/main/java/tech/pegasys/teku/cli/options/DepositOptions.java
  teku/src/test/java/tech/pegasys/teku/cli/BeaconNodeCommandTest.java
  teku/src/test/java/tech/pegasys/teku/cli/options/DepositOptionsTest.java
  teku/src/test/resources/complete_config.yaml
  teku/src/test/resources/depositOptions_config.yaml
Labels: TeamZiz

#2098 Add HeapDumpOnOutOfMemoryError flag
  build.gradle
Labels: documentation :memo:

#2091 Add --validators-graffiti command line option
  CHANGELOG.md
  teku/build.gradle
  teku/src/main/java/tech/pegasys/teku/cli/BeaconNodeCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/options/ValidatorOptions.java
  teku/src/test/java/tech/pegasys/teku/cli/options/ValidatorOptionsTest.java
  teku/src/test/resources/validatorOptions_config.yaml
  util/src/main/java/tech/pegasys/teku/util/cli/GraffitiConverter.java
  util/src/main/java/tech/pegasys/teku/util/config/TekuConfiguration.java
  util/src/main/java/tech/pegasys/teku/util/config/TekuConfigurationBuilder.java
  util/src/test/java/tech/pegasys/teku/util/cli/GraffitiConverterTest.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/Validator.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/duties/BlockProductionDuty.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/loader/ValidatorLoader.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/metrics/MetricRecordingValidatorApiChannel.java
  validator/client/src/test/java/tech/pegasys/teku/validator/client/DutySchedulerTest.java
  validator/client/src/test/java/tech/pegasys/teku/validator/client/duties/AggregationDutyTest.java
  validator/client/src/test/java/tech/pegasys/teku/validator/client/duties/AttestationProductionDutyTest.java
  validator/client/src/test/java/tech/pegasys/teku/validator/client/duties/BlockProductionDutyTest.java
Labels: TeamZiz

#2103 Demonstrate that a duplicate connection raises a PeerAlreadyConnectedException
  networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/libp2p/PeerAlreadyConnectedException.java
  networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/libp2p/PeerManager.java
  networking/p2p/src/test/java/tech/pegasys/teku/networking/p2p/libp2p/PeerManagerTest.java
Labels: TeamZiz

#2122 Change whitelist to allowlist
  CHANGELOG.md
  config/config.yaml
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/AbstractBeaconRestAPIIntegrationTest.java
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/AbstractDataBackedRestAPIIntegrationTest.java
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/beacon/RestApiHostAllowlistIntegrationTest.java
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/BeaconRestApi.java
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/HostAllowlistUtils.java
  data/beaconrestapi/src/test/java/tech/pegasys/teku/beaconrestapi/HostAllowlistUtilsTest.java
  data/metrics/src/main/java/tech/pegasys/teku/metrics/MetricsEndpoint.java
  teku/src/main/java/tech/pegasys/teku/cli/BeaconNodeCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/options/BeaconRestApiOptions.java
  teku/src/main/java/tech/pegasys/teku/cli/options/MetricsOptions.java
  teku/src/test/java/tech/pegasys/teku/cli/BeaconNodeCommandTest.java
  teku/src/test/java/tech/pegasys/teku/cli/options/BeaconRestApiOptionsTest.java
  teku/src/test/java/tech/pegasys/teku/cli/options/MetricsOptionsTest.java
  util/src/main/java/tech/pegasys/teku/util/config/TekuConfiguration.java
  util/src/main/java/tech/pegasys/teku/util/config/TekuConfigurationBuilder.java
Labels: TeamZiz, documentation :memo:

#2119 Change validator generate output to go to a single directory
  teku/src/main/java/tech/pegasys/teku/cli/deposit/DepositGenerateCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/deposit/EncryptedKeystoreWriter.java
  teku/src/test/java/tech/pegasys/teku/cli/deposit/DepositGenerateCommandTest.java
  teku/src/test/java/tech/pegasys/teku/cli/deposit/EncryptedKeystoreWriterTest.java
Labels: TeamZiz, documentation :memo:

#2083 Automate API doc with CI
  .circleci/config.yml
  docs/.circleci/config.yml
  docs/0.10.0.json
  docs/README.md
  docs/TARGET_README.md
  docs/generate-versions.js
  docs/latest.json
  docs/package.json
  docs/versions.json
Labels: documentation :memo:

#2126 reduce the stack traces produced when shutting down.
  pow/src/main/java/tech/pegasys/teku/pow/Web3jEth1Provider.java
  services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java
  util/src/main/java/tech/pegasys/teku/util/async/DelayedExecutorAsyncRunner.java
Labels: TeamZiz

#2135 remove the whitelist fallback options for the allowlist CLI parameters.
  teku/src/main/java/tech/pegasys/teku/cli/options/BeaconRestApiOptions.java
  teku/src/main/java/tech/pegasys/teku/cli/options/MetricsOptions.java
Labels: TeamZiz, documentation :memo:

#2136 make sure post /beacon/validators handles the optional epoch
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/beacon/PostValidatorsWithDataIntegrationTest.java
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/beacon/PostValidators.java
  data/provider/src/main/java/tech/pegasys/teku/api/schema/ValidatorWithIndex.java
Labels: TeamZiz

#2147 [MINOR] changelog entry for validator generate filename changes
  CHANGELOG.md
Labels: TeamZiz

#2155 allow the beaconChainController to skip forward slots if it falls behind
  ethereum/core/src/main/java/tech/pegasys/teku/core/ForkChoiceUtil.java
  ethereum/core/src/test/java/tech/pegasys/teku/core/ForkChoiceUtilTest.java
  logging/src/main/java/tech/pegasys/teku/logging/EventLogger.java
  services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java
Labels: TeamZiz

#2167 [MINOR] Use P2P in help text instead of peer to peer
  networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/network/P2PNetwork.java
  teku/src/main/java/tech/pegasys/teku/cli/options/BeaconRestApiOptions.java
  teku/src/main/java/tech/pegasys/teku/cli/options/DepositOptions.java
  teku/src/main/java/tech/pegasys/teku/cli/options/MetricsOptions.java
  teku/src/main/java/tech/pegasys/teku/cli/options/P2POptions.java
Labels: TeamZiz

#2097 Added user-friendly console logging for eth1 service success + failure.
  logging/src/main/java/tech/pegasys/teku/logging/StatusLogger.java
  pow/build.gradle
  pow/src/main/java/tech/pegasys/teku/pow/DepositFetcher.java
  pow/src/main/java/tech/pegasys/teku/pow/ErrorTrackingEth1Provider.java
  pow/src/main/java/tech/pegasys/teku/pow/Eth1DepositManager.java
  pow/src/main/java/tech/pegasys/teku/pow/Eth1HeadTracker.java
  pow/src/main/java/tech/pegasys/teku/pow/Eth1StatusLogger.java
  pow/src/main/java/tech/pegasys/teku/pow/Web3jEth1Provider.java
  pow/src/test/java/tech/pegasys/teku/pow/Eth1StatusLoggerTest.java
  services/powchain/src/main/java/tech/pegasys/teku/services/powchain/PowchainService.java
Labels: TeamZiz

#2203 Optimize: skip block validation in StateGenerator
  ethereum/core/src/main/java/tech/pegasys/teku/core/StateGenerator.java
  ethereum/core/src/main/java/tech/pegasys/teku/core/StateTransition.java
Labels: optimization 🚀

#2223 Make Altona the default network
  teku/src/main/java/tech/pegasys/teku/cli/options/NetworkOptions.java
  teku/src/test/java/tech/pegasys/teku/cli/BeaconNodeCommandTest.java
  teku/src/test/java/tech/pegasys/teku/cli/options/DepositOptionsTest.java
  teku/src/test/java/tech/pegasys/teku/cli/options/NetworkOptionsTest.java
  teku/src/test/java/tech/pegasys/teku/cli/options/P2POptionsTest.java
Labels: documentation :memo:

#2234 Add a bash/zsh autocomplete script to distributions
  build.gradle
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/debug/DebugCommand.java
Labels: documentation :memo:

#2261 Switch from Gitter to Discord
  CLA.md
  CONTRIBUTING.md
  README.md
  community-membership.md
Labels: documentation :memo:
