Repository Consensys/teku, pull requests merged in 2020-09, with the labels that each got.

#2706 BLS sign and verify against arbitrary domain separation tag (DST)
  bls/src/main/java/tech/pegasys/teku/bls/BLS.java
  bls/src/main/java/tech/pegasys/teku/bls/impl/PublicKey.java
  bls/src/main/java/tech/pegasys/teku/bls/impl/SecretKey.java
  bls/src/main/java/tech/pegasys/teku/bls/impl/Signature.java
  bls/src/main/java/tech/pegasys/teku/bls/impl/blst/BlstBLS12381.java
  bls/src/main/java/tech/pegasys/teku/bls/impl/blst/BlstSecretKey.java
  bls/src/main/java/tech/pegasys/teku/bls/impl/blst/BlstSignature.java
  bls/src/main/java/tech/pegasys/teku/bls/impl/mikuli/MikuliBLS12381.java
  bls/src/main/java/tech/pegasys/teku/bls/impl/mikuli/MikuliSecretKey.java
  bls/src/main/java/tech/pegasys/teku/bls/impl/mikuli/MikuliSignature.java
  bls/src/main/java/tech/pegasys/teku/bls/impl/noop/NoopSignature.java
  bls/src/test/java/tech/pegasys/teku/bls/BLSTest.java
Labels: TeamGroot

#2720 [Issue 2719] Update default network to medalla
  teku/src/main/java/tech/pegasys/teku/cli/options/NetworkOptions.java
  teku/src/test/java/tech/pegasys/teku/cli/BeaconNodeCommandTest.java
Labels: documentation :memo:

#2715 Persist discv5 local seqno and generated p2p private key
  gradle/versions.gradle
  logging/src/main/java/tech/pegasys/teku/logging/StatusLogger.java
  networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/Eth2NetworkBuilder.java
  networking/eth2/src/testFixtures/java/tech/pegasys/teku/networking/eth2/Eth2NetworkFactory.java
  networking/p2p/build.gradle
  networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/DiscoveryNetwork.java
  networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/discovery/discv5/DiscV5Service.java
  networking/p2p/src/test/java/tech/pegasys/teku/networking/p2p/DiscoveryNetworkTest.java
  networking/p2p/src/testFixtures/java/tech/pegasys/teku/network/p2p/DiscoveryNetworkFactory.java
  services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java
  services/beaconchain/src/test/java/tech/pegasys/teku/services/beaconchain/BeaconChainControllerTest.java
  storage/build.gradle
  storage/src/main/java/tech/pegasys/teku/storage/store/FileKeyValueStore.java
  storage/src/main/java/tech/pegasys/teku/storage/store/KeyValueStore.java
  storage/src/main/java/tech/pegasys/teku/storage/store/MemKeyValueStore.java
  storage/src/test/java/tech/pegasys/teku/storage/store/FileKeyValueStoreTest.java
  teku/src/main/java/tech/pegasys/teku/cli/slashingprotection/ImportCommand.java
Labels: documentation :memo:

#2751 Passing additional metadata to external signers
  ethereum/core/src/main/java/tech/pegasys/teku/core/signatures/LocalMessageSignerService.java
  ethereum/core/src/main/java/tech/pegasys/teku/core/signatures/LocalSigner.java
  ethereum/core/src/main/java/tech/pegasys/teku/core/signatures/MessageSignerService.java
  ethereum/core/src/main/java/tech/pegasys/teku/core/signatures/SigningRootUtil.java
  ethereum/core/src/test/java/tech/pegasys/teku/core/signatures/LocalMessageSignerServiceTest.java
  ethereum/core/src/test/java/tech/pegasys/teku/core/signatures/LocalSignerTest.java
  ethereum/core/src/testFixtures/java/tech/pegasys/teku/core/AggregateGenerator.java
  ethereum/core/src/testFixtures/java/tech/pegasys/teku/core/AttestationGenerator.java
  ethereum/core/src/testFixtures/java/tech/pegasys/teku/core/BlockProposalTestUtil.java
  ethereum/core/src/testFixtures/java/tech/pegasys/teku/core/ChainBuilder.java
  ethereum/core/src/testFixtures/java/tech/pegasys/teku/core/VoluntaryExitGenerator.java
  ethereum/core/src/testFixtures/java/tech/pegasys/teku/core/signatures/TestMessageSignerService.java
  ethereum/statetransition/build.gradle
  ethereum/statetransition/src/test/java/tech/pegasys/teku/statetransition/blockimport/BlockImporterTest.java
  ethereum/statetransition/src/testFixtures/java/tech/pegasys/teku/statetransition/BeaconChainUtil.java
  networking/eth2/src/test/java/tech/pegasys/teku/networking/eth2/gossip/topics/validation/BlockValidatorTest.java
  validator/client/build.gradle
  validator/client/src/integration-test/java/tech/pegasys/teku/validator/client/ExternalMessageSignerServiceIntegrationTest.java
  validator/client/src/integration-test/java/tech/pegasys/teku/validator/client/ExternalSignerIntegrationTest.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/loader/ValidatorLoader.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/ExternalMessageSignerService.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/ExternalSigner.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/SignType.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/SigningRequestBody.java
  validator/client/src/test/java/tech/pegasys/teku/validator/client/signer/SignerTest.java
Labels: TeamGroot, documentation :memo:

#2812 add teku bootnode for Spadina.
  util/src/main/java/tech/pegasys/teku/util/config/NetworkDefinition.java
Labels: documentation :memo:

#2820 Update slashing protection interchange format version to v.4
  data/dataexchange/src/main/java/tech/pegasys/teku/data/SlashingProtectionExporter.java
  data/dataexchange/src/main/java/tech/pegasys/teku/data/SlashingProtectionImporter.java
  data/dataexchange/src/main/java/tech/pegasys/teku/data/slashinginterchange/CompleteSigningHistory.java
  data/dataexchange/src/main/java/tech/pegasys/teku/data/slashinginterchange/InterchangeFormat.java
  data/dataexchange/src/main/java/tech/pegasys/teku/data/slashinginterchange/Metadata.java
  data/dataexchange/src/main/java/tech/pegasys/teku/data/slashinginterchange/SignedAttestation.java
  data/dataexchange/src/main/java/tech/pegasys/teku/data/slashinginterchange/SignedBlock.java
  data/dataexchange/src/main/java/tech/pegasys/teku/data/slashinginterchange/SigningHistory.java
  data/dataexchange/src/main/java/tech/pegasys/teku/data/slashinginterchange/SlashingProtectionInterchangeFormat.java
  data/dataexchange/src/test/java/tech/pegasys/teku/data/slashinginterchange/MetadataTest.java
  data/dataexchange/src/test/java/tech/pegasys/teku/data/slashinginterchange/MinimalSigningHistoryTest.java
  data/dataexchange/src/test/java/tech/pegasys/teku/data/slashinginterchange/SigningHistoryTest.java
  data/dataexchange/src/test/resources/format1_complete.json
  data/dataexchange/src/test/resources/format2_minimal.json
  data/dataexchange/src/test/resources/invalid_json.json
  data/dataexchange/src/test/resources/metadata.json
  data/dataexchange/src/test/resources/minimal_invalidKey.json
  data/dataexchange/src/test/resources/oldMetadata.json
Labels: documentation :memo:
