Repository Consensys/teku, pull requests merged in 2020-05, with the labels that each got.

#1728 update documentation and API documentation URLs
  README.md
Labels: bug 🐞, documentation :memo:

#1757 made loglevel case insensitive
  teku/src/test/java/tech/pegasys/teku/cli/BeaconNodeCommandTest.java
  util/src/main/java/tech/pegasys/teku/util/cli/LogTypeConverter.java
Labels: TeamZiz

#1772 updated the response type of get /beacon/committees to array
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/beacon/GetCommittees.java
Labels: TeamZiz

#1695 Publish openapi to gh pages
  .circleci/config.yml
Labels: documentation :memo:

#1808 1798 - update chainHead to use bestBlockAndState
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/beacon/GetHead.java
  data/beaconrestapi/src/test/java/tech/pegasys/teku/beaconrestapi/handlers/beacon/GetChainHeadTest.java
  data/beaconrestapi/src/test/java/tech/pegasys/teku/beaconrestapi/handlers/beacon/GetHeadTest.java
  data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java
  data/provider/src/main/java/tech/pegasys/teku/api/schema/BeaconChainHead.java
  data/provider/src/main/java/tech/pegasys/teku/api/schema/BeaconHead.java
  data/provider/src/test/java/tech/pegasys/teku/api/ChainDataProviderTest.java
  data/provider/src/test/java/tech/pegasys/teku/api/schema/BeaconChainHeadTest.java
Labels: TeamZiz

#1804 Move api doc
  .gitignore
  CONTRIBUTING.md
  GOVERNANCE.md
  community-membership.md
  docs/0.10.0.json
  docs/README.md
  docs/code-reviews.md
  docs/generate-versions.js
  docs/index.html
  docs/latest.json
  docs/package-lock.json
  docs/package.json
  docs/versions.json
Labels: documentation :memo:

#1801 custom exception for Public Key parsing
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/beacon/PostValidators.java
  data/beaconrestapi/src/test/java/tech/pegasys/teku/beaconrestapi/handlers/beacon/PostValidatorsTest.java
  data/provider/src/main/java/tech/pegasys/teku/api/schema/BLSPubKey.java
  data/provider/src/main/java/tech/pegasys/teku/api/schema/PublicKeyException.java
Labels: TeamZiz

#1822 add extra context for err
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/beacon/PostValidators.java
  data/beaconrestapi/src/test/java/tech/pegasys/teku/beaconrestapi/handlers/beacon/PostValidatorsTest.java
Labels: TeamZiz

#1821 1800 - /beacon/block now returns block root
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/beacon/GetBlockWithDataIntegrationTest.java
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/beacon/GetBlock.java
  data/beaconrestapi/src/test/java/tech/pegasys/teku/beaconrestapi/handlers/beacon/GetBlockTest.java
  data/provider/src/main/java/tech/pegasys/teku/api/ChainDataProvider.java
  data/provider/src/main/java/tech/pegasys/teku/api/response/GetBlockResponse.java
  data/provider/src/test/java/tech/pegasys/teku/api/ChainDataProviderTest.java
Labels: TeamZiz

#1815 Add CI job for api doc generation on master
  .circleci/config.yml
  docs/latest.json
Labels: documentation :memo:

#1834 catch FileNotFoundException and display helpful error message
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/PeerCommand.java
  teku/src/test/java/tech/pegasys/teku/cli/subcommand/PeerCommandTest.java
Labels: TeamZiz

#1900 don't overwrite file if it exists
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/PeerCommand.java
  teku/src/test/java/tech/pegasys/teku/cli/subcommand/PeerCommandTest.java
Labels: TeamZiz

#1909 Improved error messages around loading validator keys via YAML + tests.
  validator/client/src/main/java/tech/pegasys/teku/validator/client/loader/YamlValidatorKeyProvider.java
  validator/client/src/test/java/tech/pegasys/teku/validator/client/loader/YamlValidatorKeyProviderTest.java
Labels: TeamZiz

#1967 added rest-api-host-whitelist
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/AbstractBeaconRestAPIIntegrationTest.java
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/AbstractDataBackedRestAPIIntegrationTest.java
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/BeaconRestApi.java
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/HostWhitelistUtils.java
  data/beaconrestapi/src/test/java/tech/pegasys/teku/beaconrestapi/HostWhitelistUtilsTest.java
  teku/src/main/java/tech/pegasys/teku/cli/BeaconNodeCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/options/BeaconRestApiOptions.java
  teku/src/test/java/tech/pegasys/teku/cli/BeaconNodeCommandTest.java
  teku/src/test/java/tech/pegasys/teku/cli/options/BeaconRestApiOptionsTest.java
  util/src/main/java/tech/pegasys/teku/util/config/TekuConfiguration.java
  util/src/main/java/tech/pegasys/teku/util/config/TekuConfigurationBuilder.java
Labels: TeamZiz

#1986 [MINOR] suppress warning
  ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/util/ValidatorsUtil.java
Labels: TeamZiz

#1983 [MINOR] added units
  teku/src/main/java/tech/pegasys/teku/cli/options/ValidatorOptions.java
Labels: TeamZiz

#1985 Change camel case options
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/GenesisCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/PeerCommand.java
Labels: TeamZiz

#1837 1412 - added channels for streaming block events back from storage
  bls/src/main/java/tech/pegasys/teku/bls/BLSPublicKey.java
  bls/src/main/java/tech/pegasys/teku/bls/BLSSignature.java
  ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/operations/DepositWithIndex.java
  ethereum/datastructures/src/testFixtures/java/tech/pegasys/teku/datastructures/util/DataStructureUtil.java
  pow/src/main/java/tech/pegasys/teku/pow/event/MinGenesisTimeBlockEvent.java
  services/chainstorage/build.gradle
  services/chainstorage/src/main/java/tech/pegasys/teku/services/chainstorage/ChainStorageService.java
  services/chainstorage/src/main/java/tech/pegasys/teku/services/chainstorage/StorageService.java
  storage/build.gradle
  storage/src/main/java/tech/pegasys/teku/storage/api/Eth1DepositStorageChannel.java
  storage/src/main/java/tech/pegasys/teku/storage/server/ChainStorage.java
  storage/src/main/java/tech/pegasys/teku/storage/server/Database.java
  storage/src/main/java/tech/pegasys/teku/storage/server/DepositStorage.java
  storage/src/main/java/tech/pegasys/teku/storage/server/ReplayDepositsResult.java
  storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/RocksDbDatabase.java
  storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/dataaccess/RocksDbDao.java
  storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/dataaccess/V3RocksDbDao.java
  storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/schema/V3Schema.java
  storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/serialization/DepositsFromBlockEventSerializer.java
  storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/serialization/MinGenesisTimeBlockEventSerializer.java
  storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/serialization/RocksDbSerializer.java
  storage/src/test/java/tech/pegasys/teku/storage/server/AbstractDatabaseTest.java
  storage/src/test/java/tech/pegasys/teku/storage/server/DepositStorageTest.java
  storage/src/test/java/tech/pegasys/teku/storage/server/rocksdb/serialization/DepositsFromBlockSerializerTest.java
  storage/src/test/java/tech/pegasys/teku/storage/server/rocksdb/serialization/MinGenesisTimeBlockEventSerializerTest.java
  storage/src/testFixtures/java/tech/pegasys/teku/storage/InMemoryStorageSystem.java
  teku/src/main/java/tech/pegasys/teku/services/ServiceController.java
Labels: TeamZiz

#1975 refactor PeerCommand to use PicoCLI exceptions
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/PeerCommand.java
  teku/src/test/java/tech/pegasys/teku/cli/subcommand/PeerCommandTest.java
Labels: TeamZiz

#1991 1761 - append to logfile on startup
  logging/src/main/java/tech/pegasys/teku/logging/LoggingConfigurator.java
Labels: TeamZiz

#1995 Print information about validators on startup
  teku/src/main/java/tech/pegasys/teku/BeaconNode.java
  teku/src/main/java/tech/pegasys/teku/cli/deposit/EncryptedKeystoreWriter.java
  util/src/main/java/tech/pegasys/teku/util/bytes/KeyFormatter.java
  util/src/test/java/tech/pegasys/teku/util/bytes/KeyFormatterTest.java
  validator/client/src/main/java/tech/pegasys/teku/validator/client/loader/ValidatorLoader.java
Labels: TeamZiz

#1994 Removed --eth1-enabled option.
  teku/src/main/java/tech/pegasys/teku/cli/BeaconNodeCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/options/DepositOptions.java
  teku/src/test/java/tech/pegasys/teku/cli/BeaconNodeCommandTest.java
  teku/src/test/java/tech/pegasys/teku/cli/options/DepositOptionsTest.java
  teku/src/test/resources/depositOptions_config.yaml
  util/src/main/java/tech/pegasys/teku/util/config/TekuConfiguration.java
  util/src/main/java/tech/pegasys/teku/util/config/TekuConfigurationBuilder.java
Labels: TeamZiz

#1981 Added new ValidatorOptions validation rule and improved readability of existing error + tests.
  util/src/main/java/tech/pegasys/teku/util/config/TekuConfiguration.java
  util/src/test/java/tech/pegasys/teku/util/config/TekuConfigurationTest.java
Labels: TeamZiz

#2002 [MINOR] added output
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/PeerCommand.java
Labels: TeamZiz

#2008 rest api whitelist changelog entry
  CHANGELOG.md
Labels: TeamZiz

#2012 [CHANGELOG] link to changelog
  README.md
Labels: TeamZiz

#2010 [CHANGELOG] subcommand changes
  CHANGELOG.md
Labels: TeamZiz

#2009 [CHANGELOG] consistency of messages
  CHANGELOG.md
Labels: TeamZiz

#2011 move storage/api to its own module
  ethereum/statetransition/build.gradle
  gradle/check-licenses.gradle
  networking/eth2/build.gradle
  services/beaconchain/build.gradle
  services/chainstorage/build.gradle
  settings.gradle
  storage/api/build.gradle
  storage/api/src/main/java/tech/pegasys/teku/storage/api/Eth1DepositStorageChannel.java
  storage/api/src/main/java/tech/pegasys/teku/storage/api/FinalizedCheckpointChannel.java
  storage/api/src/main/java/tech/pegasys/teku/storage/api/ReorgEventChannel.java
  storage/api/src/main/java/tech/pegasys/teku/storage/api/StorageQueryChannel.java
  storage/api/src/main/java/tech/pegasys/teku/storage/api/schema/ReplayDepositsResult.java
  storage/build.gradle
  storage/src/main/java/tech/pegasys/teku/storage/server/DepositStorage.java
  storage/src/test/java/tech/pegasys/teku/storage/server/DepositStorageTest.java
  sync/build.gradle
  validator/anticorruption/build.gradle
  validator/coordinator/build.gradle
Labels: TeamZiz
