Repository Consensys/teku, pull requests merged in 2021-05, with the labels that each got.

#3987 Update YML load code and prevent job to crash silently
  .openapidoc/config.js
  .openapidoc/publish.js
Labels: bug 🐞

#4004 add link checker
  .github/workflows/check-links-nightly.yml
  .github/workflows/check-links.yml
  CONTRIBUTING.md
  GOVERNANCE.md
  README.md
  community-membership.md
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/README.md
  data/dataexchange/README.md
  mlc_config.json
Labels: code style 💅

#4011 added slashing protection repair command
  data/dataexchange/build.gradle
  data/dataexchange/src/main/java/tech/pegasys/teku/data/SlashingProtectionRepairer.java
  data/dataexchange/src/test/java/tech/pegasys/teku/data/SlashingProtectionRepairerTest.java
  services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/WeakSubjectivityInitializer.java
  teku/build.gradle
  teku/src/main/java/tech/pegasys/teku/cli/options/Eth2NetworkOptions.java
  teku/src/main/java/tech/pegasys/teku/cli/slashingprotection/ExportCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/slashingprotection/ImportCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/slashingprotection/RepairCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/subcommand/SlashingProtectionCommand.java
  teku/src/main/java/tech/pegasys/teku/cli/util/SlashingProtectionCommandUtils.java
Labels: documentation :memo:
