Repository Consensys/teku, pull requests merged in 2023-08, with the labels that each got.

#7258 store non canonical blob sidecars
  services/chainstorage/src/main/java/tech/pegasys/teku/services/chainstorage/StorageService.java
  storage/api/src/main/java/tech/pegasys/teku/storage/api/StorageQueryChannel.java
  storage/src/integration-test/java/tech/pegasys/teku/storage/server/kvstore/DatabaseTest.java
  storage/src/main/java/tech/pegasys/teku/storage/server/ChainStorage.java
  storage/src/main/java/tech/pegasys/teku/storage/server/CombinedStorageChannelSplitter.java
  storage/src/main/java/tech/pegasys/teku/storage/server/Database.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/KvStoreDatabase.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/dataaccess/CombinedKvStoreDao.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/dataaccess/KvStoreCombinedDao.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/dataaccess/KvStoreCombinedDaoAdapter.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/dataaccess/V4FinalizedKvStoreDao.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/schema/SchemaCombined.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/schema/SchemaFinalizedSnapshotStateAdapter.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/schema/V6SchemaCombinedSnapshot.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/schema/V6SchemaCombinedTreeState.java
  storage/src/main/java/tech/pegasys/teku/storage/server/noop/NoOpDatabase.java
  storage/src/main/java/tech/pegasys/teku/storage/server/pruner/BlobSidecarPruner.java
  storage/src/test/java/tech/pegasys/teku/storage/server/pruner/BlobSidecarPrunerTest.java
  storage/src/testFixtures/java/tech/pegasys/teku/storage/api/StubStorageQueryChannel.java
  teku/src/main/java/tech/pegasys/teku/cli/options/BeaconNodeDataOptions.java
Labels: doc-change-required, Epic Deneb

#7442 Added Holesky network configuration
  CHANGELOG.md
  ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java
  ethereum/spec/src/main/java/tech/pegasys/teku/spec/networks/Eth2Network.java
  ethereum/spec/src/main/resources/tech/pegasys/teku/spec/config/configs/holesky.yaml
  ethereum/spec/src/test/java/tech/pegasys/teku/spec/SpecFactoryTest.java
Labels: doc-change-required

#7453 add non canonical blob sidecars fallback
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/AbstractDataBackedRestAPIIntegrationTest.java
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/v1/beacon/GetBlobSidecarsIntegrationTest.java
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/v1/beacon/GetBlockHeadersIntegrationTest.java
  data/provider/src/main/java/tech/pegasys/teku/api/blobselector/BlobSidecarSelectorFactory.java
  data/provider/src/test/java/tech/pegasys/teku/api/blobselector/BlobSidecarSelectorFactoryTest.java
  ethereum/spec/src/testFixtures/java/tech/pegasys/teku/spec/generator/ChainBuilder.java
  storage/src/main/java/tech/pegasys/teku/storage/client/CombinedChainDataClient.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/KvStoreDatabase.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/dataaccess/CombinedKvStoreDao.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/dataaccess/KvStoreCombinedDao.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/dataaccess/KvStoreCombinedDaoAdapter.java
  storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/dataaccess/V4FinalizedKvStoreDao.java
Labels: Epic Deneb

#7456 refactor get non canonical blob sidecars test
  data/beaconrestapi/src/integration-test/java/tech/pegasys/teku/beaconrestapi/v1/beacon/GetBlobSidecarsIntegrationTest.java
Labels: Epic Deneb
