Repository Consensys/teku, pull requests merged in 2024-07, with the labels that each got.

#8413 PART 1 - GetPeerCount validator api channel
  beacon/validator/src/integrationTest/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandlerIntegrationTest.java
  beacon/validator/src/main/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandler.java
  beacon/validator/src/test/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandlerTest.java
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/tekuv1/admin/Readiness.java
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/v1/node/GetPeerCount.java
  data/beaconrestapi/src/test/java/tech/pegasys/teku/beaconrestapi/handlers/v1/node/GetPeerCountTest.java
  data/provider/src/main/java/tech/pegasys/teku/api/NetworkDataProvider.java
  data/provider/src/test/java/tech/pegasys/teku/api/NetworkDataProviderTest.java
  ethereum/json-types/src/main/java/tech/pegasys/teku/ethereum/json/types/node/PeerCount.java
  ethereum/json-types/src/main/java/tech/pegasys/teku/ethereum/json/types/node/PeerCountBuilder.java
  services/beaconchain/src/main/java/tech/pegasys/teku/services/beaconchain/BeaconChainController.java
  validator/api/src/main/java/tech/pegasys/teku/validator/api/ValidatorApiChannel.java
  validator/beaconnode/src/main/java/tech/pegasys/teku/validator/beaconnode/metrics/BeaconNodeRequestLabels.java
  validator/beaconnode/src/main/java/tech/pegasys/teku/validator/beaconnode/metrics/MetricRecordingValidatorApiChannel.java
  validator/remote/src/main/java/tech/pegasys/teku/validator/remote/FailoverValidatorApiHandler.java
  validator/remote/src/main/java/tech/pegasys/teku/validator/remote/RemoteValidatorApiHandler.java
  validator/remote/src/main/java/tech/pegasys/teku/validator/remote/sentry/SentryValidatorApiChannel.java
Labels: bn-failovers

#8414 PART 2 - GetPeerCount remote validator api channel handler
  ethereum/json-types/src/main/java/tech/pegasys/teku/ethereum/json/types/node/PeerCount.java
  validator/remote/src/integration-test/java/tech/pegasys/teku/validator/remote/typedef/handlers/GetPeerCountRequestTest.java
  validator/remote/src/integration-test/resources/responses/get_peer_count.json
  validator/remote/src/main/java/tech/pegasys/teku/validator/remote/RemoteValidatorApiHandler.java
  validator/remote/src/main/java/tech/pegasys/teku/validator/remote/apiclient/ValidatorApiMethod.java
  validator/remote/src/main/java/tech/pegasys/teku/validator/remote/typedef/OkHttpValidatorTypeDefClient.java
  validator/remote/src/main/java/tech/pegasys/teku/validator/remote/typedef/handlers/GetPeerCountRequest.java
  validator/remote/src/test/java/tech/pegasys/teku/validator/remote/RemoteValidatorApiHandlerTest.java
Labels: bn-failovers

#8415 PART 3 - consider connected peers count when selecting a BN failover
  validator/remote/src/main/java/tech/pegasys/teku/validator/remote/BeaconNodeReadinessManager.java
  validator/remote/src/test/java/tech/pegasys/teku/validator/remote/BeaconNodeReadinessManagerTest.java
Labels: bn-failovers

#8431 PART 1 - GET/Attestation Pool API - Handle Electra attestations in the aggregating pool
  ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/AggregatingAttestationPool.java
  ethereum/statetransition/src/test/java/tech/pegasys/teku/statetransition/attestation/AggregatingAttestationPoolTest.java
Labels: EIP7549

#8462 Migrate Teku to Java 21
  .circleci/config.yml
  .github/workflows/codeql.yml
  CHANGELOG.md
  README.md
  beacon/sync/src/main/java/tech/pegasys/teku/beacon/sync/forward/multipeer/batches/SyncSourceBatch.java
  beacon/sync/src/main/java/tech/pegasys/teku/beacon/sync/forward/singlepeer/PeerSync.java
  build.gradle
  docker/jdk17/Dockerfile
  eth-reference-tests/src/referenceTest/java/tech/pegasys/teku/reference/phase0/ssz_generic/SszGenericContainerTestExecutor.java
  fork-choice-tests/src/integration-test/java/tech/pegasys/teku/forkChoiceTests/ForkChoiceIntegrationTest.java
  gradle/versions.gradle
  infrastructure/ssz/src/main/java/tech/pegasys/teku/infrastructure/ssz/tree/SszNodeTemplate.java
  infrastructure/ssz/src/test/java/tech/pegasys/teku/infrastructure/ssz/schema/TreeNodeAssert.java
  infrastructure/ssz/src/testFixtures/java/tech/pegasys/teku/infrastructure/ssz/RandomSszDataGenerator.java
  infrastructure/ssz/src/testFixtures/java/tech/pegasys/teku/infrastructure/ssz/SszDataAssert.java
  infrastructure/ssz/src/testFixtures/java/tech/pegasys/teku/infrastructure/ssz/SszTestUtils.java
Labels: doc-change-required

#8471 Add GetAttesterSlashingV2 implementation
  data/beaconrestapi/src/integration-test/resources/tech/pegasys/teku/beaconrestapi/beacon/schema/GetPoolAttesterSlashingsV2Response.json
  data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/v2/beacon/GetAttesterSlashingsV2.java
  data/beaconrestapi/src/test/java/tech/pegasys/teku/beaconrestapi/handlers/v2/beacon/GetAttesterSlashingsV2Test.java
  data/beaconrestapi/src/test/resources/tech/pegasys/teku/beaconrestapi/handlers/v2/beacon/getAttesterSlashingsELECTRA.json
  data/beaconrestapi/src/test/resources/tech/pegasys/teku/beaconrestapi/handlers/v2/beacon/getAttesterSlashingsPHASE0.json
  data/provider/src/main/java/tech/pegasys/teku/api/NodeDataProvider.java
  data/provider/src/test/java/tech/pegasys/teku/api/NodeDataProviderTest.java
Labels: EIP7549
